flipperdevices/Flipper-Android-App

components/bridge/api/src/main/java/com/flipperdevices/bridge/api/model/FlipperRequest.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/overflow/FlipperRequestComparator.kt
components/bridge/impl/src/test/java/com/flipperdevices/bridge/impl/manager/overflow/FlipperRequestComparatorTest.kt
components/bridge/impl/src/test/java/com/flipperdevices/bridge/impl/manager/overflow/FlipperRequestStorageTest.kt

**Background**
Now we can shuffle our requests to flipper. It can cause bugs, when you send request, where order is important.
**Changes**
- Improve comparator
- Request with highest timestamp have largest priority (when priority is equals)
**Test plan**
- Try upload large file

Fix request order

---

build.gradle.kts
settings.gradle.kts

**Background**
allprojects/subprojects blocks should be avoided, because it adds additional complexity for build configuration, that could be avoided by using convention plugins and special contructs as `dependencyResolutionManagement`, also it blocks configureOnDemand and incoming ['project-isolation'](https://gradle.github.io/configuration-cache/#constraints_for_build_scripts_and_plugins) feature
**Changes**
Use new centralized block for dependency resolution
**Test plan**
dependency resolution trigger for all configuration will show a problem with repository configuration
simple current PR build will be enough

use dependencyResolutionManagement block

---

components/bottombar/impl/src/main/AndroidManifest.xml

**Background**
Now sometimes we use fragment `BottomNavigationFragment` as activity
https://sentry.flipperdevices.com/organizations/flipper/issues/64/
**Changes**
- Remove `BottomNavigationFragment` declaration as Activity
**Test plan**
Merge it and see if crash happens with newest version in sentry

Remove fragment as activity

---

buildSrc/settings.gradle.kts
components/core/markdown/build.gradle.kts
gradle/libs.versions.toml
settings.gradle.kts

**Background**
Now application crash in internal and production release
```
Caused by: java.lang.IllegalArgumentException: No enum constant gd.d.a.P
at java.lang.Enum.valueOf(Enum.java:257)
at ed.b.c(BitFieldSet.java:9)
at ed.b.f(BitFieldSet.java:1)
at gd.d.<clinit>(ISegmentBuilder.java:3)
at gd.l.<init>(SequenceBuilder.java:6) 
at fd.d.W(BasedSequenceImpl.java:1) 
at fd.m.t(SegmentedSequence.java:1) 
at xc.c.h0(Block.java:1) 
at tc.k.h(ParagraphParser.java:2) 
```
**Changes**
- Downgrade flexmark, because https://github.com/vsch/flexmark-java/issues/442 not fixed
- Remove feature preview toggle for `VERSION_CATALOGS`
**Test plan**
Build internal release
Run it

Fix crash in internal release

---

.github/workflows/release_candidate.yml
buildSrc/src/main/java/commonAndroid.kt

**Background**
Now RC version naming is "-internal-rc", but we expect "-rc" for RC release build and "-internal-rc" for internal build of RC
**Changes**
- Now release and internal is different jobs
**Test plan**
See https://github.com/flipperdevices/Flipper-Android-App/actions/runs/1854443531

Fix RC naming

---

components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/api/parsers/url/FFFUrlEncoder.kt
components/keyscreen/impl/build.gradle.kts
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/viewmodel/KeyScreenViewModel.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/viewmodel/ShareDelegate.kt

**Background**
Now if we want share to Slack, we share image, not link
Also we encode `/`
**Changes**
- Not encode `/` for improve readability of link
- Remove code for image preview
**Test plan**

Remove image share preview and fix encoding for url

---

components/info/impl/src/main/java/com/flipperdevices/info/impl/compose/elements/ComposableFirmwareUpdate.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/compose/elements/InfoElementCard.kt

**Background**
Now we have error with align
**Changes**
Fix potential bug with this

Fix unsupported dialog in device info screen

---

CHANGELOG.md
components/bridge/api/src/main/java/com/flipperdevices/bridge/api/manager/FlipperLagsDetector.kt
components/bridge/api/src/main/java/com/flipperdevices/bridge/api/utils/Constants.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/FlipperBleManagerImpl.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/service/request/FlipperRequestApiImpl.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/service/request/FlipperSerialApiUnsafeImpl.kt
components/bridge/service/impl/src/main/java/com/flipperdevices/bridge/service/impl/FlipperServiceApiImpl.kt
components/bridge/service/impl/src/main/java/com/flipperdevices/bridge/service/impl/delegate/FlipperLagsDetectorImpl.kt
components/bridge/service/impl/src/main/java/com/flipperdevices/bridge/service/impl/utils/WeakConnectionStateProvider.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/SynchronizationTask.kt

**Background**
Sometimes we have infinite synchronization. So we can restart connection if we see similar problem
**Changes**
- Add lags detector
**Test plan**
Try use flipper with buggy rpc. You can reproduce it with this patch:
```
diff --git a/firmware/targets/f7/ble_glue/serial_service.c b/firmware/targets/f7/ble_glue/serial_service.c
index a5d3b97a..9e011477 100644
--- a/firmware/targets/f7/ble_glue/serial_service.c
+++ b/firmware/targets/f7/ble_glue/serial_service.c
@@ -217,6 +217,7 @@ bool serial_svc_update_tx(uint8_t* data, uint16_t data_len) {
return false;
}
+    furi_crash("Test RPC freeze");
for(uint16_t remained = data_len; remained > 0;) {
uint8_t value_len = MIN(SERIAL_SVC_CHAR_VALUE_LEN_MAX, remained);
uint16_t value_offset = data_len - remained;
```

Add timeout for each pending request

---

CHANGELOG.md
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/viewmodel/SaveDelegate.kt

**Background**
Now we can cancel editing key
**Changes**
* Add condition equals old/new key after cancel editing key
**Test plan**
* Choose key
* Select Edit
* Do something changes
* Click 'Cancel'
* Look for key information didn't change

Fix possibility cancel editing keys

---

CHANGELOG.md
components/bridge/dao/api/src/main/java/com/flipperdevices/bridge/dao/api/model/FlipperKeyContent.kt

**Background**
Now we crash application if file for `InternalFile` is not exist
**Changes**
- Just return empty stream for not-exist file

Fix crash when file content is empty

---

CHANGELOG.md
components/info/impl/src/main/java/com/flipperdevices/info/impl/compose/bar/ComposableDeviceBar.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/compose/bar/ComposableFlipperBattery.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/model/DeviceStatus.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/viewmodel/DeviceStatusViewModel.kt
components/info/impl/src/main/res/drawable/ic_charging.xml

**Background**
Now we don't show if flipper charge now
**Changes**
- Show when flipper charging
- Fix incorrect corner radius for battery icon
**Test plan**
Connect flipper to charger and check that flipper app shown them

Add charging state and fix corner radius for battery

---

CHANGELOG.md
components/firstpair/impl/src/main/res/values/strings.xml

**Background**
* Dynamic links in the documentation can change, so we want to replace them with a deep link template
**Changes**
*  Replace in string resource link
**Test plan**
* Going to First Pair screen and click to links

Replace dynamic link on static template deeplink

---

CHANGELOG.md
components/singleactivity/api/build.gradle.kts
components/singleactivity/impl/src/main/java/com/flipperdevices/singleactivity/impl/SingleActivity.kt
components/singleactivity/impl/src/main/java/com/flipperdevices/singleactivity/impl/SingleActivityHolder.kt
components/singleactivity/impl/src/main/java/com/flipperdevices/singleactivity/impl/api/SingleActivityApiImpl.kt
components/updater/impl/src/main/java/com/flipperdevices/updater/impl/UpdaterTask.kt
components/updater/screen/src/main/java/com/flipperdevices/updater/screen/fragments/UpdaterFragment.kt
components/updater/screen/src/main/java/com/flipperdevices/updater/screen/viewmodel/UpdaterViewModel.kt

**Background**
Now we have bugs with update navigation. When we cancel update and e.t.c
**Changes**
- Not open single activity if it already open
- Hide update image when update finished
**Test plan**
Try cancel update, try lock phone when update in progress

Fixes update navigation

---

CHANGELOG.md
components/info/impl/src/main/java/com/flipperdevices/info/impl/compose/info/ComposableFirmwareVersion.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/model/DeviceInfo.kt
components/info/shared/src/main/java/com/flipperdevices/info/shared/ComposableDeviceInfoRow.kt
components/info/shared/src/main/java/com/flipperdevices/info/shared/ComposableFirmwareVersion.kt
components/info/shared/src/main/res/values/strings.xml
components/updater/api/src/main/java/com/flipperdevices/updater/model/FirmwareChannel.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/composable/ComposableFirmwareVersionValueChoice.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/viewmodel/UpdateCardViewModel.kt
components/updater/impl/build.gradle.kts
components/updater/impl/src/main/java/com/flipperdevices/updater/impl/utils/FirmwareVersionBuildHelper.kt
components/updater/impl/src/test/kotlin/com/flipperdevices/updater/impl/FirmwareVersionBuildHelperTest.kt

**Background**
Support unknown firmware https://github.com/flipperdevices/Flipper-Android-App/issues/234
**Changes**
* New value for enum FirmwareChanel
* Update flag 'always update' if we connected with unknown firmware 
* Update parser version string to FirmwareVersion (like qFlipper https://github.com/flipperdevices/qFlipper/blob/7aeb2b595da4eabdfe16e270834777c2c1033aa7/backend/flipperzero/helper/deviceinfohelper.cpp#L262) + test
**Test plan**
Connect application to flipper with unknown firmware

Support unknown firmware

---

CHANGELOG.md
components/nfceditor/impl/src/main/java/com/flipperdevices/nfceditor/impl/composable/ComposableNfcCell.kt
components/nfceditor/impl/src/main/java/com/flipperdevices/nfceditor/impl/composable/ComposableNfcEditor.kt
components/nfceditor/impl/src/main/java/com/flipperdevices/nfceditor/impl/composable/ComposableScaleFactorCalculate.kt
components/nfceditor/impl/src/main/java/com/flipperdevices/nfceditor/impl/composable/card/ComposableNfcCard.kt
components/nfceditor/impl/src/main/java/com/flipperdevices/nfceditor/impl/composable/card/ComposableSchemeCard.kt

**Background**
Now we overlaps when screen is too small
**Changes**
- Use fontSize instead of width of each text field
**Test plan**
Try open screen on small phone

Fix incorrect rescale for nfc editor

---

CHANGELOG.md
components/singleactivity/impl/src/main/java/com/flipperdevices/singleactivity/impl/SingleActivity.kt
components/singleactivity/impl/src/main/java/com/flipperdevices/singleactivity/impl/api/SingleActivityApiImpl.kt

**Background**
We can't provide new deep link if application open
**Changes**
Process deeplink if activity exist
Log if we can't pop deeplink
**Test plan**
* Open app
* Going to some deep link
* In app you can see result on deeplink

Deeplik open if activity exist

---

CHANGELOG.md
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/FlipperBleManagerImpl.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/service/requestservice/FlipperRtcUpdateService.kt

**Background**
Now if user using only Android, flipper never has correct time
**Changes**
- Update time on each connection to Flipper
**Test plan**
Try launch flipper and then check time on Flipper

Update RTC on Flipper by Android App

---

CHANGELOG.md
components/bridge/service/impl/src/main/java/com/flipperdevices/bridge/service/impl/delegate/FlipperAutoDisconnect.kt
components/singleactivity/impl/build.gradle.kts
components/singleactivity/impl/src/main/java/com/flipperdevices/singleactivity/impl/SingleActivity.kt

**Background**
Sometimes we don't need execute connect, but in resume in SingleActivity we always execute it
**Changes**
- Now execute connectIfNotForceDisconnect only in FlipperAutoDisconnect
**Test plan**
Check that connectIfNotForceDisconnect not execute in first pair screens

Execute connectIfNotForceDisconnect in FlipperAutoDisconnect

---

CHANGELOG.md
components/updater/card/src/main/java/com/flipperdevices/updater/card/viewmodel/UpdateCardViewModel.kt

**Background**
Now, if we have error on updater screen, we see error state after click retry
**Changes**
Setup state in progress after retry, because get information from flipper/fw server - its heavy
**Test plan**

Not change state updater card after retry

---

CHANGELOG.md
components/filemanager/impl/src/main/AndroidManifest.xml

**Background**
Now we can't use 3rd file manager for upload file on android 11+
**Changes**
Update manifest for GetContent
**Test plan**
Try upload file from 3rd file picker

Update manifest for 3rd file manager by android 11+

---

CHANGELOG.md
components/bridge/api/src/main/java/com/flipperdevices/bridge/api/scanner/DiscoveredBluetoothDevice.kt
components/bridge/api/src/main/java/com/flipperdevices/bridge/api/utils/Constants.kt
components/bridge/impl/build.gradle.kts
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/scanner/FlipperScannerImpl.kt
components/bridge/impl/src/test/java/com/flipperdevices/bridge/impl/scanner/FlipperScannerImplTest.kt
gradle/libs.versions.toml

**Background**
Now we are not looking for objects that do not match by name - some flippers may give an invalid name or mac address.
**Changes**
- Added new condition to the device filter by mac address
- Added `FlipperScannerImplTest`
**Test plan**
Try to find a flipper with an empty name
Fix #335

Search for devices by Mac address and by flipper name (Fix #335)

---

CHANGELOG.md
build-logic/gradle/wrapper/gradle-wrapper.properties
build-logic/settings.gradle.kts
gradle.properties
gradle/wrapper/gradle-wrapper.properties
settings.gradle.kts

**Background**
Speed up builds. Prepare for gradle 8.0.
Details about `STABLE_CONFIGURATION_CACHE` flag [here](https://docs.gradle.org/7.5.1/release-notes.html#:~:text=New%20STABLE_CONFIGURATION_CACHE%20feature%20flag).
**Changes**
Enable gradle configuration cache. Set the build to fail if the configuration cache has a warning.
**Test plan**
Green pipelines. Local build successful. The configuration cache is stored and reused.

Enable gradle configuration cache

---

CHANGELOG.md
components/bridge/dao/api/src/main/java/com/flipperdevices/bridge/dao/api/delegates/key/SimpleKeyApi.kt
components/bridge/dao/api/src/main/java/com/flipperdevices/bridge/dao/api/model/FlipperFileType.kt
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/api/key/SimpleKeyApiImpl.kt
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/repository/key/SimpleKeyDao.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/api/SynchronizationApiImpl.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/repository/KeysSynchronization.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/repository/android/SynchronizationStateRepository.kt
components/nfceditor/impl/src/main/java/com/flipperdevices/nfceditor/impl/viewmodel/NfcEditorStateProducerHelper.kt

**Background**
Right now we have bugs with synchronization and shadow files
**Changes**
- Create a shadow file when editing a card even if there is no shadow file
- Mark all keys that are present at the moment as synchronized
**Test plan**
Try renaming the file back and forth. For example, "Office.nfc"->"Office_1.nfc" -> "Office.nfc".
Behavior with old firmware: never sync
Behavior with new firmware: synchronizes

Fix synchronization status with shadow files

---

.github/workflows/internal.yml
.github/workflows/release.yml
.github/workflows/release_candidate.yml

**Background**
Right now we have deprecated CI for RC and release
**Changes**
- Upload gms and nogms in release and release candidate
**Test plan**
Run it on dev

Change CI for RC and release

---

CHANGELOG.md
components/core/share/src/main/kotlin/com/flipperdevices/core/share/SharableFile.kt
components/core/ui/res/src/main/res/drawable/ic_double_back.xml
components/core/ui/res/src/main/res/drawable/ic_screenshot.xml
components/screenstreaming/impl/build.gradle.kts
components/screenstreaming/impl/src/main/java/com/flipperdevices/screenstreaming/impl/composable/ButtonEnum.kt
components/screenstreaming/impl/src/main/java/com/flipperdevices/screenstreaming/impl/composable/ComposableControlButtons.kt
components/screenstreaming/impl/src/main/java/com/flipperdevices/screenstreaming/impl/composable/ComposableScreen.kt
components/screenstreaming/impl/src/main/java/com/flipperdevices/screenstreaming/impl/composable/ComposableStreamingScreen.kt
components/screenstreaming/impl/src/main/java/com/flipperdevices/screenstreaming/impl/viewmodel/FlipperRequestApiButtonKtx.kt
components/screenstreaming/impl/src/main/java/com/flipperdevices/screenstreaming/impl/viewmodel/ScreenStreamingViewModel.kt
components/screenstreaming/impl/src/main/res/values/strings.xml

**Background**
Right now we can't do screenshot and unlock flipper by one button
**Changes**
Add unlock button
Add screenshot button
**Test plan**
Try lock flipper and unlock via unlock button
Try screenshot flipper

Add screenshot and unlock button in screenstreaming

---

CHANGELOG.md
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/api/key/DeleteKeyApiImpl.kt

**Background**
Right now when we delete key from trash and this key exist in favorites, app throw crash
**Changes**
Delete key before permanently delete from trash
**Test plan**
- Add key to favorite
- Move it to trash
- Delete it from trash

Fix crash when delete from trash key with favorites

---

CHANGELOG.md
components/share/uploader/src/main/kotlin/com/flipperdevices/uploader/viewmodel/UploaderViewModel.kt

**Background**
Bump length for server-side share link
**Changes**
From 200 to 256
**Test plan**
Try share link

Bump length for server-side share link

---

CHANGELOG.md
components/bridge/api/src/main/java/com/flipperdevices/bridge/api/manager/service/FlipperVersionApi.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/service/FlipperVersionApiImpl.kt
components/bridge/rpcinfo/impl/src/main/java/com/flipperdevices/bridge/rpcinfo/impl/FlipperRpcInformationApiImpl.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/repository/flipper/TimestampSynchronizationChecker.kt
components/keyscreen/emulate/src/main/java/com/flipperdevices/keyscreen/emulate/viewmodel/helpers/FlipperErrorHelper.kt
components/updater/subghz/src/main/kotlin/com/flipperdevices/updater/subghz/helpers/SkipProvisioningHelper.kt
components/updater/subghz/src/test/kotlin/com/flipperdevices/updater/subghz/tasks/SkipProvisioningHelperTest.kt

**Background**
Right now we each time request version and wait until version is provided
**Changes**
- Share this logic in version api class
- Use isSupported method 
**Test plan**
Try launch application and check version support

Migrate VersionApi to isSupported

---

CHANGELOG.md
components/bottombar/impl/src/main/java/com/flipperdevices/bottombar/impl/composable/ComposableInAppNotification.kt
components/bottombar/impl/src/main/java/com/flipperdevices/bottombar/impl/viewmodel/InAppNotificationViewModel.kt
components/core/ktx/src/main/java/com/flipperdevices/core/ktx/android/ComposeLifecycleKtx.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/composable/searching/ComposableSearchingView.kt
components/inappnotification/impl/src/main/java/com/flipperdevices/inappnotification/impl/storage/InAppNotificationStorageImpl.kt
components/screenstreaming/impl/src/main/java/com/flipperdevices/screenstreaming/impl/composable/ComposableStreamingScreen.kt

**Background**
Right now we crush if subscriber already exist, because our compose screens can be in situation with same screen instance on screen in one moment
**Changes**
- Not crush if subscribe already exist
- Migrate lifecycle to more safe lifecycle event API
- Use disposable when it possible
**Test plan**
Try use screenstreaming and inappstorage

Fix startup crush with inapp storage

---

CHANGELOG.md
components/widget/screen/src/main/java/com/flipperdevices/widget/screen/viewmodel/WidgetSelectViewModel.kt

**Background**
Right now when we set state with customize button on widget screen we don't update widget state
**Changes**
Reset widget state after change key associated
**Test plan**
Try emulate key which not synchronized and then change key with customize button

Fix customize button when set widget state

---

CHANGELOG.md
components/bridge/api/src/main/java/com/flipperdevices/bridge/api/utils/Constants.kt

**Background**
Right now we wait too more for reconnecting 
**Changes**
- Decrease pending commands timeout in lags detector
- Decrease reconnecting timeout
**Test plan**
Try reconnecting flipper

Decrease timeouts

---

CHANGELOG.md
components/bridge/api/src/main/java/com/flipperdevices/bridge/api/manager/service/RestartRPCApi.kt
components/bridge/api/src/main/java/com/flipperdevices/bridge/api/utils/Constants.kt
components/bridge/impl/build.gradle.kts
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/FlipperBleManagerImpl.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/UnsafeBleManager.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/overflow/FlipperSerialOverflowThrottler.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/service/RestartRPCApiImpl.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/utils/BridgeImplConfig.kt
components/bridge/service/api/src/main/java/com/flipperdevices/bridge/service/api/FlipperServiceApi.kt
components/bridge/service/impl/src/main/java/com/flipperdevices/bridge/service/impl/FlipperServiceApiImpl.kt
components/bridge/service/impl/src/main/java/com/flipperdevices/bridge/service/impl/delegate/FlipperLagsDetectorImpl.kt
components/settings/impl/src/main/java/com/flipperdevices/settings/impl/viewmodels/DebugViewModel.kt
gradle/libs.versions.toml

**Background**
Right now reset api work incorrectly
**Changes**
- Invalidate lags detector more ofter
- Wait for disconnect when restart rpc
- Request reconnect when restart rpc
- Migrate to not deprecated approach in FlipperBleManager
- Fix reset in flipper serial overflow throttler
**Test plan**
Try press on restart rpc in debug options

Wait disconnecting from device when restart rpc

---

CHANGELOG.md
components/analytics/shake2report/impl/src/main/java/com/flipperdevices/analytics/shake2report/impl/composable/states/ComposableReportError.kt
components/analytics/shake2report/impl/src/main/java/com/flipperdevices/analytics/shake2report/impl/composable/states/ComposableReportSuccessful.kt
components/bridge/rpcinfo/impl/src/main/java/com/flipperdevices/bridge/rpcinfo/impl/mapper/DeprecatedFlipperRpcInfoMapper.kt
components/bridge/rpcinfo/impl/src/main/java/com/flipperdevices/bridge/rpcinfo/impl/mapper/NewFlipperRpcInfoMapper.kt
components/bridge/rpcinfo/impl/src/main/java/com/flipperdevices/bridge/rpcinfo/impl/mapper/RpcInformationInfoHelper.kt
components/bridge/rpcinfo/impl/src/test/java/com/flipperdevices/bridge/rpcinfo/impl/mapper/DeviceInfoHelperTest.kt

**Background**
Replace radio type to radio type number from device info
**Changes**
For example, in previous variant we have Major.Minor.Type(Type Name)
And now we have Major.Minor.Sub(Type Name)
**Test plan**
Try open device info and see radio stack in Major.Minor.Sub(Type Name) format

Replace radio type to radio sub number in device info

---

CHANGELOG.md
components/updater/screen/src/main/java/com/flipperdevices/updater/screen/composable/ComposableUpdaterScreen.kt

**Background**
Now, if we click cancel update, application crashes
**Changes**
* return function, not Box scope
**Test plan**
Try update Flipper and click cancel on diff states

Crash application on cancel update

---

CHANGELOG.md
components/faphub/fapscreen/impl/src/main/java/com/flipperdevices/faphub/fapscreen/impl/composable/header/ComposableFapBuildStatus.kt

**Background**
Right now we hide info icon instead of warning icon
**Changes**
- Remove boolean flag for remove info icon
- Hide warning icon
**Test plan**
See preview

Fix faphub build status hide icon instead of info

---

CHANGELOG.md
components/info/impl/src/main/java/com/flipperdevices/info/impl/compose/screens/ComposableDeviceInfoScreen.kt
components/updater/api/src/main/java/com/flipperdevices/updater/api/UpdaterCardApi.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/api/UpdaterCardApiImpl.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/composable/ComposableUpdaterCard.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/viewmodel/UpdateCardViewModel.kt

**Background**
Right now we can't invalidate info screen
**Changes**
Refresh updater card when pull
**Test plan**
Try use pull to refresh on info screen

Add pull to refresh update for update card

---

CHANGELOG.md
components/bridge/rpcinfo/impl/src/main/java/com/flipperdevices/bridge/rpcinfo/impl/stats/FlipperRpcStatsCollector.kt

**Background**
Right now we can't update via bluetooth from 0.64.3
https://www.youtube.com/watch?v=kqxCcuQkvTc
**Changes**
- Check in FlipperRpcStatsCollector RPC
**Test plan**
Try update from https://update.flipperzero.one/builds/firmware/0.64.3/?C=S&O=A

FlipperRpcStatsCollector checks rpc version before request

---

CHANGELOG.md
gradle/libs.versions.toml

**Background**
Right now we have failed CI pipeline
**Changes**
Downgrade sentry gradle plugin until backend not updated
**Test plan**
Try upload proguard files to sentry server

Downgrade sentry gradle

---

CHANGELOG.md
components/faphub/fapscreen/impl/src/main/res/drawable/ic_report.xml
components/faphub/fapscreen/impl/src/main/res/values/strings.xml
components/faphub/report/impl/src/main/kotlin/com/flipperdevices/faphub/report/impl/composable/ComposableReadyToReport.kt
components/faphub/report/impl/src/main/res/values/strings.xml

**Background**
Right now we can send empty report from faphub
**Changes**
- Update report app icon
- Change Report App title
**Test plan**
Try report empty description

Not send empty report in faphub

---

CHANGELOG.md
components/selfupdater/impl/src/main/kotlin/com/flipperdevices/selfupdater/impl/api/SelfUpdaterApiImpl.kt
components/selfupdater/unknown/src/main/kotlin/com/flipperdevices/selfupdater/unknown/api/SelfUpdaterUnknown.kt

**Background**
Now we have crash on install
**Changes**
Return no updates on unknown source
**Test plan**
Try to install app from unknown source

Fix crash on appication from unknown source

---

CHANGELOG.md
components/screenstreaming/impl/src/main/java/com/flipperdevices/screenstreaming/impl/viewmodel/ScreenStreamingViewModel.kt

**Background**
Right now we have vibration in iOS, but don't have in Android
**Changes**
- Add vibration in app
**Test plan**
Try press on button in screenstreaming

Add button vibration in ScreenStreaming

---

CHANGELOG.md
components/screenstreaming/impl/src/main/java/com/flipperdevices/screenstreaming/impl/viewmodel/repository/StreamingRepository.kt

**Background**
Right now we just show not connected/in progress when flipper disconnect/connected in screen streaming
**Changes**
- Restore screen streaming when flipper reconnect
**Test plan**
Try reconnect flipper in screen streaming

Fix lost connection in screen streaming

---

CHANGELOG.md
components/core/markdown/build.gradle.kts
components/core/markdown/src/main/java/com/flipperdevices/core/markdown/ComposableMarkdown.kt
components/faphub/fapscreen/impl/build.gradle.kts
components/faphub/report/impl/build.gradle.kts
components/updater/screen/build.gradle.kts
gradle/libs.versions.toml

**Background**
Right now we use programistich's fork for markdown
**Changes**
Use upstream markdown renderer library
**Test plan**
Try build and see how markdown looks

Migrate to markdown renderer from upstream

---

CHANGELOG.md
components/core/progress/build.gradle.kts
components/core/progress/src/test/java/com/flipperdevices/core/progress/ProgressWrapperTrackerTest.kt

**Background**
This PR is responsible for supporting Unit-tests to improve the stability and test coverage of the project as part of the `Stability project`. It covers all cases of the `ProgressWrapperTracker` class. 
**Changes**
- Create `ProgressWrapperTrackerTest `
- Provide testing dependencies in the gradle file  
**Test plan**
- Run Unit-test of the core/progress module

Support Unit-test for the ProgressWrapperTracker class

---

CHANGELOG.md
components/deeplink/impl/src/main/java/com/flipperdevices/deeplink/impl/parser/delegates/DeepLinkFlipperFormatSharing.kt

**Background**
Right now, when we use the "Open in App" button on the /sf share screen we see an error screen
**Changes**
- As fallback we try parse both format of deeplink
**Test plan**
Try open deeplink from "Open in App" button on browser page

Fix crash on sf import

---

CHANGELOG.md
components/core/ktx/src/androidMain/kotlin/com/flipperdevices/core/ktx/android/BitmapKtx.kt
components/faphub/screenshotspreview/impl/src/main/kotlin/com/flipperdevices/faphub/screenshotspreview/impl/viewmodel/UrlImageShareViewModel.kt
components/screenstreaming/impl/src/main/java/com/flipperdevices/screenstreaming/impl/viewmodel/ScreenshotViewModel.kt

**Background**
When sharing screenshot on ScreenshotPreview screen it looks like screenshot very blurry. It's actually not blured, but low-resolutioned.
**Changes**
- Created BitmapKtx where rescale operation of bitmap is shared
**Test plan**
- Open flipper apps screenshots screen
- Share a screenshot 
- See screenshot now doesn't looks blurry

Fix low resolution of saved screenshots

---

CHANGELOG.md
components/faphub/screenshotspreview/impl/src/main/kotlin/com/flipperdevices/faphub/screenshotspreview/impl/viewmodel/UrlImageShareViewModel.kt
components/screenstreaming/impl/src/main/java/com/flipperdevices/screenstreaming/impl/viewmodel/ScreenshotViewModel.kt

**Background**
The format of saved files on remote control and screenshots preview can't be saved [via TotalCommander](https://ghisler.ch/board/viewtopic.php?t=52215&start=15) and on some devices with Google Photo
**Changes**
- Fixed format of files just like in `ShareFullInfoFileViewModel` `"yyyy-MM-dd-HH-mm-ss"`
**Test plan**
- Open Remote Control on screenshots preview
- Click share image and save it via TotalCommander
- See now the format is `"yyyy-MM-dd-HH-mm-ss"` and it saved correctly

Fix unable to save screenshot

---

.github/workflows/call-create-baseline.yml

**Background**
Fix wrong path for baseline file
**Changes**
- Fixed baseline file path, [example](https://github.com/makeevrserg/Flipper-Android-App/actions/runs/8848621091/job/24301163092)
**Test plan**
- Run ci

Fix baseline file path

---

CHANGELOG.md
components/faphub/installation/manifest/api/src/main/java/com/flipperdevices/faphub/installation/manifest/model/FapManifestItem.kt
components/faphub/installation/manifest/impl/build.gradle.kts
components/faphub/installation/manifest/impl/src/main/java/com/flipperdevices/faphub/installation/manifest/impl/utils/FapManifestParser.kt
components/faphub/installation/manifest/impl/src/main/java/com/flipperdevices/faphub/installation/manifest/impl/utils/FapManifestsLoader.kt
components/faphub/installation/queue/impl/build.gradle.kts
components/faphub/installation/queue/impl/src/main/java/com/flipperdevices/faphub/installation/queue/impl/executor/InstallationActionExecutor.kt
components/faphub/installation/stateprovider/impl/src/test/kotlin/com/flipperdevices/faphub/installation/stateprovider/impl/api/FapInstallationStateManagerImplTest.kt
components/faphub/installedtab/impl/src/test/kotlin/com/flipperdevices/faphub/installedtab/impl/viewmodel/TestManifestBuilder.kt

**Background**
Right now flipper mobile app doesn't filter aps from prod/dev catalog. Because of this, after switching do dev catalog, apps from prod is displayed and vice versa
**Changes**
- Provided changes are the same as in [Flipper-iOS-App](https://github.com/flipperdevices/Flipper-iOS-App/commit/26553e7b7099ff349a631d39993571aa426c19d4)
- Added flag `isDevCatalog` to `FapManifestItem`
- Add filter inside `FapManifestsLoader` for `isDevCatalog`
> [!WARNING]  
> All installed apps which doesn't has a flag of `isDevCatalog` will return `isDevCatalog=false`
**Test plan**
1. [Optionally] delete all other apps for easier testing
2. Turn on usage of dev catalog
3. Install dev catalog apps
4. Turn off dev catalog
5. Open installed apps and see no dev-catalog apps present
6. Repeat steps 2-5 …

Fix filter dev catalog apps

---

.github/workflows/call-create-baseline.yml
.github/workflows/internal.yml
CHANGELOG.md
build-logic/plugins/convention/src/main/kotlin/com/flipperdevices/buildlogic/ApkConfig.kt
instances/android/baselineprofile/build.gradle.kts

**Background**
Right now we are using the default GitHub Action SDK built in as our Android SDK. This makes our builds unstable and dependent on GitHub release processes. 
**Changes**
- Use https://github.com/android-actions/setup-android for setup android sdk
**Test plan**
See https://github.com/flipperdevices/Flipper-Android-App/actions/runs/8985960551

Using third-party Github Action Setup Android SDK for baseline profile generation

---

CHANGELOG.md
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/composable/bar/ComposableEditorTopBar.kt

**Background**
Edit File screen in FileManager currently doesn't have paddings for systembar
**Changes**
- Added system bar padding for Edit File screen on FileManager
**Test plan**
- Open  File manager
- Open some file to edit
- See TopBar now doesn't collapse inside systembar

Fix file manager edit file screen padding

---

CHANGELOG.md
components/updater/api/src/main/java/com/flipperdevices/updater/api/FirmwareVersionBuilderApi.kt
components/updater/impl/src/main/java/com/flipperdevices/updater/impl/api/FirmwareVersionBuilderApiImpl.kt
components/updater/impl/src/test/kotlin/com/flipperdevices/updater/impl/FirmwareVersionBuildHelperTest.kt

**Background**
Right now we have problems with custom firmware version
**Changes**
Use as version full string which received from Flipper even if this string is unparselable
**Test plan**
Try use custom branch on flipper

Fix custom version detection

---

CHANGELOG.md
components/faphub/installation/manifest/impl/src/main/java/com/flipperdevices/faphub/installation/manifest/impl/utils/FapManifestsLoader.kt

**Background**
On Hub->Installed sd card error displayed even if it's loaded. This happens because of long `cacheLoader.loadCache` operation
**Changes**
- Added initial state before `cacheLoader.loadCache` operation
**Test plan**
- Open Hub->Installed
- See SD Card error now does not display as long as before
- Additionaly add more logs ore debug breakpoint into `FapManifestsLoader` to see `NoSdCardException` message

Fix sd card not mounted display

---

.github/workflows/pr.yml
.github/workflows/pr_changelog.yml
.github/workflows/pr_gradle.yml
CHANGELOG.md
test_file

**Background**
When creating pull requests and pushing multiple commits one after another, previous pipelines are not cancelld and continue to run, even if they are now useless
**Changes**
- Here added concurrency for pull requests commits
- When new pull request is pushed, the old pipelines of this PR will be cancelled 
**Test plan**
- See this PR
- See after few pushes previous jobs is cancelled

add github ci PR concurrency cancellation

---

CHANGELOG.md
components/core/ktx/src/androidMain/kotlin/com/flipperdevices/core/ktx/android/UriKtx.kt

**Background**
Now we can get write access to the internal files. Now this doesn't give direct access to the user's files, but it serves as a very dangerous step towards potential other vulnerabilities
More info: https://github.com/flipperdevices/Flipper-Android-App/issues/877
**Changes**
- Now the file name is obtained using `File(filename).name`, which eliminates the use of the path traversal vulnerability
**Test plan**
Try run apk from attached issue
Co-authored-by: LiveOverflow <liveoverflow@gmail.com>

Fix for a vulnerability causing write access to internal application files

---

CHANGELOG.md
components/bridge/service/impl/src/main/java/com/flipperdevices/bridge/service/impl/FlipperService.kt
components/inappnotification/impl/src/main/java/com/flipperdevices/inappnotification/impl/composable/type/ComposableInAppNotificationSelfUpdateReady.kt
components/selfupdater/thirdparty/api/src/main/kotlin/com/flipperdevices/selfupdater/thirdparty/api/SelfUpdaterThirdParty.kt
components/wearable/emulate/handheld/impl/src/main/java/com/flipperdevices/wearable/emulate/handheld/impl/service/WearRequestForegroundService.kt

**Background**
With the new update and the target sdk update we started crashing when start foreground service without permissions
**Changes**
- Added check for permishen when starting services
- Fixed self updater 3-rd party. Fixed paddings
**Test plan**
Try opening the wearos app before the onboarding pass. It would have crashed before

Fix check permission for foreground service

---

CHANGELOG.md
components/remote-controls/setup/api/src/main/kotlin/com/flipperdevices/remotecontrols/api/DispatchSignalApi.kt
components/remote-controls/setup/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/setup/composable/SetupScreen.kt
components/remote-controls/setup/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/setup/composable/components/LoadedContent.kt
components/remote-controls/setup/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/setup/presentation/decompose/SetupComponent.kt
components/remote-controls/setup/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/setup/presentation/decompose/internal/SetupComponentImpl.kt
components/remote-controls/setup/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/setup/presentation/viewmodel/DispatchSignalViewModel.kt

**Background**
When selecting signal inside Infrared remote setup - the "bottom sheet" displayed from the beginning. It should be displayed only when  signal is dispatched.
**Changes**
- Add state to display "bottom sheet" only after signal is dispatched
**Test plan**
- Open signal select screen
- Press signal
- See the confirm menu animated and shown only after signal is dispatched
- Press yes/no
- See "bottom sheet" is hidden again

Fix expandable signal verify

---

.github/workflows/call-create-baseline.yml
.github/workflows/internal.yml

**Background**
After relocating on self-hosted runners baseline generator is broken. This PR adding missing linux packaged with sudo ./gradlew as it requires permissions
**Changes**
- Add libx11
- add platform-android-sdk34
**Test plan**
- See [this action](https://github.com/flipperdevices/Flipper-Android-App/actions/runs/9989676210/job/27608801873)

fix avd linux baseline

---

CHANGELOG.md
components/core/ktx/src/androidMain/kotlin/com/flipperdevices/core/ktx/android/RemoveBondHelper.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/composable/searching/ComposableSearching.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/composable/searching/ComposableSearchingDevices.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/viewmodels/connecting/PairDeviceViewModel.kt
components/firstpair/impl/src/test/kotlin/com/flipperdevices/firstpair/impl/viewmodels/connecting/PairDeviceViewModelTest.kt

**Background**
Right now the Retry button on a failed peering error does nothing and just reconnects it
**Changes**
- Deletion of Bond on repeat request
**Test plan**
Try reconnect to/from flipper with changed mac address
https://github.com/flipperdevices/flipperzero-firmware/pull/3723

Remove bond on retry pair

---

CHANGELOG.md
components/faphub/installation/manifest/impl/src/main/java/com/flipperdevices/faphub/installation/manifest/impl/utils/FapManifestCacheLoader.kt
components/faphub/installation/manifest/impl/src/main/java/com/flipperdevices/faphub/installation/manifest/impl/utils/FapManifestsLoader.kt

**Background**
Right now we're trying to load even those manifest files that are created with a dot at the beginning - that's usually how they mark those files that are deleted
**Changes**
- Add filter for start with point
**Test plan**
Try sync app

Ignore manifests with dot in start

---

.github/workflows/call-check-changelog.yml
.github/workflows/call-create-baseline.yml
.github/workflows/call-gradle-cache.yml
.github/workflows/call-validate-gradle-wrapper.yml
.github/workflows/internal.yml
.github/workflows/pr.yml
.github/workflows/release.yml
CHANGELOG.md

**Background**
Right now, CI  creating different actions for one event. This PR introduces improvement by using workflow-calls. With this PRs actions located inside one workflow and not splitted inside actions GitHub page
**Changes**
- Move changelog, gradle-cache, validation to workflow-calls
- Use ubuntu-latest for lighweight tasks instead of self-hosted
**Test plan**
- See this PR CI
- See [DEV](https://github.com/makeevrserg/Flipper-Android-App/actions/runs/10198634797)
- See [PR](https://github.com/makeevrserg/Flipper-Android-App/actions/runs/10198630466)

Merge CI actions

---

CHANGELOG.md
components/remote-controls/setup/api/src/main/kotlin/com/flipperdevices/remotecontrols/api/DispatchSignalApi.kt
components/remote-controls/setup/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/setup/composable/SetupScreen.kt
components/remote-controls/setup/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/setup/composable/components/ConfirmContent.kt
components/remote-controls/setup/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/setup/composable/components/LoadedContent.kt
components/remote-controls/setup/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/setup/presentation/decompose/SetupComponent.kt
components/remote-controls/setup/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/setup/presentation/decompose/internal/SetupComponentImpl.kt
components/remote-controls/setup/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/setup/presentation/viewmodel/DispatchSignalViewModel.kt

**Background**
On setup screen of infrared remotes bottom sheet animation has bad behaviour on state change
**Changes**
- Use transitions to implement target state and current state for bottom sheet animation
**Test plan**
- Open setup screen
- Press button, waith for bottom sheet opened with beautiful animation
- Click yes or no and see another beautiful close animation

Fix wrong animation confirm setup

---

CHANGELOG.md
components/remote-controls/api-backend/src/commonMain/kotlin/com/flipperdevices/ifrmvp/backend/model/SignalRequestModel.kt
components/remote-controls/setup/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/setup/composable/SetupScreen.kt
components/remote-controls/setup/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/setup/composable/components/ConfirmContent.kt
components/remote-controls/setup/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/setup/presentation/decompose/SetupComponent.kt
components/remote-controls/setup/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/setup/presentation/decompose/internal/SetupComponentImpl.kt
components/remote-controls/setup/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/setup/presentation/viewmodel/CurrentSignalViewModel.kt
components/remote-controls/setup/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/setup/presentation/viewmodel/HistoryViewModel.kt
components/remote-controls/setup/impl/src/main/res/values/strings.xml

**Background**
When setup of remote in progress, some button can be not avaliable, thus we need to skip them instead of yes/no
**Changes**
- Add signal skip backend integration
**Test plan**
- Open setup and try skip some buttons

add skip for signals

---

CHANGELOG.md
components/remote-controls/grid/saved/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/grid/local/composable/LocalGridComposable.kt
components/remote-controls/grid/saved/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/grid/local/composable/components/GridOptions.kt
components/remote-controls/grid/saved/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/grid/local/presentation/decompose/LocalGridComponent.kt
components/remote-controls/grid/saved/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/grid/local/presentation/decompose/internal/LocalGridComponentImpl.kt
components/remote-controls/grid/saved/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/grid/local/presentation/viewmodel/LocalGridViewModel.kt
components/remote-controls/grid/saved/impl/src/main/res/values/strings.xml
components/remote-controls/setup/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/setup/composable/SetupScreen.kt
components/remote-controls/setup/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/setup/composable/components/ButtonContent.kt
components/remote-controls/setup/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/setup/composable/components/ConfirmContent.kt
components/remote-controls/setup/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/setup/composable/components/LoadedContent.kt
components/remote-controls/setup/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/setup/presentation/decompose/SetupComponent.kt
components/remote-controls/setup/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/setup/presentation/decompose/internal/SetupComponentImpl.kt
components/remote-controls/setup/impl/src/main/res/values/strings.xml

**Background**
The bottom sheet on setup remote control is displayed above bottom bar. This pr wrap it inside dialog and shows on top of  bottombar
**Changes**
-  Wrap confirm display inside dialog to display it on top of screen
**Test plan**
- Open setup menu
- Press button to see bottomsheet
- Press back or yes/no/skip 
- See it good animated and displayed on top of screen

Fix bottombar bottomsheet

---

CHANGELOG.md
components/remote-controls/grid/saved/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/grid/local/composable/LocalGridComposable.kt
components/remote-controls/grid/saved/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/grid/local/composable/components/GridOptions.kt
components/remote-controls/grid/saved/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/grid/local/presentation/decompose/internal/LocalGridScreenDecomposeComponentImpl.kt

**Background**
We can't currently share the ui with ir file
**Changes**
- Remove share from remote controls screen
**Test plan**
- Open saved remote control screen 
- See there's no share option

remove share from remote controls

---

CHANGELOG.md
components/faphub/installation/button/impl/src/main/java/com/flipperdevices/faphub/installation/button/impl/helper/OpenFapHelper.kt

**Background**
Right now we pass "RPC" argument to app load request for screen streaming
**Changes**
- Remove "RPC" argument
**Test plan**
Try launch app via "Open" button in faphub

Remove "RPC" argument from screen streaming request

---

CHANGELOG.md
components/toolstab/impl/src/main/java/com/flipperdevices/toolstab/impl/composable/elements/RemoteControlsComposable.kt

**Background**
Current infrared card has grey color of "beta text"
**Changes**
- Change color of beta text on infrared color
**Test plan**
- Open tools tab
- See green text on beta text card

Remotes fix beta color

---

CHANGELOG.md
components/toolstab/impl/src/main/res/values/strings.xml

**Background**
Update the description of remotes library
**Changes**
- Changed strings.xml value
**Test plan**
- Open tools tab and see new description

change remotes library desc

---

CHANGELOG.md
components/deeplink/impl/src/main/java/com/flipperdevices/deeplink/impl/parser/delegates/DeepLinkFlipperFormatSharing.kt
components/keyparser/impl/src/main/kotlin/com/flipperdevices/keyparser/impl/api/KeyParserImpl.kt

**Background**
Right now we have bug with deeplink handling on some bad devices
**Changes**
- Add in deeplink parse fallback query segment apply
- Improve logging for deeplink parse
**Test plan**
Try open link from browser. For example, https://flpr.app/sf/#path=nfc/Volna_11.nfc&key=-9iAwAho85pFALQKZEc2Bg&id=ReRwXA

Add deeplink fallback for flipper scheme uri

---

CHANGELOG.md
components/analytics/metric/noop/src/main/java/com/flipperdevices/metric/noop/NoopMetricAndroidApiImpl.kt

**Background**
Android Project can't be build with disabled metrics due to it's inject in SingleActivity  #988 
**Changes**
- Add NoOp for AndroiMetricsApi
**Test plan**
- Assemble project with disabled metrics

fix build when metrics disabled

---

components/bridge/connection/config/api/src/commonMain/kotlin/com/flipperdevices/bridge/connection/config/api/FDevicePersistedStorage.kt
components/bridge/connection/config/impl/src/commonMain/kotlin/com/flipperdevices/bridge/connection/config/impl/FDevicePersistedStorageImpl.kt
components/bridge/connection/feature/protocolversion/impl/src/commonMain/kotlin/com/flipperdevices/bridge/connection/feature/protocolversion/impl/api/FSdkVersionFeatureFactoryImpl.kt
components/nfc/mfkey32/api/build.gradle.kts
components/nfc/mfkey32/api/src/main/java/com/flipperdevices/nfc/mfkey32/api/MfKey32Api.kt
components/nfc/mfkey32/screen/build.gradle.kts
components/nfc/mfkey32/screen/src/main/java/com/flipperdevices/nfc/mfkey32/screen/api/MfKey32ApiImpl.kt
components/nfc/mfkey32/screen/src/main/java/com/flipperdevices/nfc/mfkey32/screen/viewmodel/ExistedKeysStorage.kt
components/nfc/mfkey32/screen/src/main/java/com/flipperdevices/nfc/mfkey32/screen/viewmodel/MfKey32ViewModel.kt

**Background**
Just migration of mfkey32 to new api
**Changes**
- Only migrated mfkey32
**Test plan**
- Use mfkey32 feature and see it's the same as before

Migrate mfkey32 to new api
