.github/workflows/android.yml
.travis.yml

- Add upload artifact
- Add check unit test

Add Github Actions CI

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/flipper/app/App.kt
app/src/main/res/layout/activity_main.xml
core/build.gradle
gradle.properties

- Add gradle deps properties
- Add Timber in app module

Add Timber

---

README.md
app/build.gradle.kts
app/src/main/java/com/flipper/app/MainActivity.kt
app/src/main/java/com/flipper/app/home/HomeController.kt
app/src/main/java/com/flipper/app/home/HomePresenter.kt
app/src/main/java/com/flipper/app/home/HomeView.kt
app/src/main/res/layout/controller_home.xml
app/src/main/res/values/strings.xml
bridge/build.gradle.kts
buildSrc/src/main/java/Dependencies.kt
buildSrc/src/main/java/com/flipper/gradle/AppExtensionConfiguration.kt
buildSrc/src/main/java/com/flipper/gradle/LibraryExtensionConfiguration.kt
core/build.gradle.kts
core/src/main/java/com/flipper/core/view/BaseController.kt
core/src/main/java/com/flipper/core/view/ViewInflater.kt

Add Conductor
Add Moxy
Add Conductor+Moxy sample

Add Moxy and Conductor

---

.idea/codeStyles/Project.xml
app/src/main/java/com/flipper/app/home/di/HomeScreenModule.kt
app/src/main/java/com/flipper/app/home/ui/data/HomeTab.kt
app/src/main/java/com/flipper/app/stub/StubController.kt
core/build.gradle.kts
core/src/main/java/com/flipper/core/view/BaseController.kt
integration-test/src/main/java/com/flipper/integrationtest/CounterController.kt
ktlint

**Background**
Now we have wrong style in project
**Changes**
I update ktlint and just fix all issue
**Test plan**
Run `./ktlint`

Some refactor, update ktlint

---

.github/workflows/internal.yml
.github/workflows/pr.yml
app/src/main/java/com/flipper/app/home/ui/HomePresenter.kt
app/src/main/java/com/flipper/app/stub/StubPresenter.kt
buildSrc/build.gradle.kts
buildSrc/src/main/java/Dependencies.kt
core/src/test/java/com/flipper/core/BaseControllerTest.kt
gradle/wrapper/gradle-wrapper.properties
integration-test/build.gradle.kts
integration-test/src/main/java/com/flipper/integrationtest/CounterPresenter.kt

**Background**
I want try update android gradle plugin and gradle to newest release version
**Changes**
- Up Kotlin from `1.4.0` to `1.5.21`
- Up Gradle from `6.1.1` to `7.0.2`
- Up AGP from `4.0.1` to `7.0.1`
- Up JDK from `1.8` to `1.11`
- Up Dagger from `2.28.3` to `2.38.1`
- Up Moxy from `2.1.2` to `2.2.2`
**Test plan**
- Build project

Update gradle, agp, kotlin to lastest versions

---

buildSrc/src/main/java/com/flipper/gradle/ConfigurationPlugin.kt
components/bridge/build.gradle.kts
components/bridge/src/main/java/com/flipper/bridge/impl/manager/FlipperBleManager.kt
components/core/build.gradle.kts
components/core/src/main/java/com/flipper/core/models/BLEDevice.kt
components/core/src/main/java/com/flipper/core/utils/Fragment.kt
components/info/build.gradle.kts
components/pair/build.gradle.kts
instances/app/build.gradle.kts

**Background**
Here i have some comments about code quality: https://github.com/flipperdevices/Flipper-Android-App/pull/58
**Changes**
- Remove from `ConfigurationPlugin` autoset for gradle modules
- Replace to `StateFlow` object in `FlipperBleManager`
- Replace `if` to `check` 
**Test plan**
Pass github checks

Fix review comments

---

components/bridge/build.gradle.kts
components/bridge/src/main/java/com/flipper/bridge/impl/manager/FlipperBleManager.kt
components/bridge/src/main/java/com/flipper/bridge/impl/scanner/FlipperScannerImpl.kt
components/bridge/src/main/java/com/flipper/bridge/impl/viewmodel/FlipperViewModel.kt
components/bridge/src/main/java/com/flipper/bridge/utils/Constants.kt
components/info/build.gradle.kts
components/info/src/main/java/com/flipper/info/main/InfoFragment.kt
components/info/src/main/java/com/flipper/info/main/compose/ComposeInfoScreen.kt
components/info/src/main/java/com/flipper/info/main/service/FlipperViewModel.kt
components/info/src/main/res/drawable/ic_baseline_send_24.xml

**Background**
With newest firmware version you can use echo from/to flipper
**Changes**
- Add echo screen
**Test plan**
Open information screen
Type text and send

Add echo screen

---

buildSrc/build.gradle.kts
buildSrc/src/main/java/Dependencies.kt
components/pair/src/main/java/com/flipper/pair/PairScreenActivity.kt
gradle.properties

**Background**
Improve build speed and refactoring
**Changes**
- Enable non transitive r class
- Update gradle
- Update deps
**Test plan**
- Just pass all CI checks

Update gradle and deps and add non transitive r class

---

components/bridge/src/main/java/com/flipper/bridge/impl/pair/FlipperPairApiImpl.kt

**Background**
Now we drop connection when device disable bluetooth
**Changes**
Autoconnect with device
**Test plan**
- Open info screen
- Disable bluetooth on flipper
- Enable bluetooth on flipper

Use autoconnect

---

components/pair/src/main/java/com/flipper/pair/find/FindDeviceFragment.kt

**Background**
Now we close pair screen just after open
**Changes**
- Remove pass pair screen if we have saved device
**Test plan**
Click to connect to another device button

Remove pass pair screen if we have saved device

---

buildSrc/src/main/java/com/flipperdevices/gradle/AppExtensionConfiguration.kt
buildSrc/src/main/java/com/flipperdevices/gradle/LibraryExtensionConfiguration.kt
components/analytics/shake2report/src/debug/AndroidManifest.xml

**Background**
Now we crash when build internal release
**Changes**
- Change source set for internal to debug
- Add new sentry endpoint

Fix internal source set

---

components/analytics/shake2report/src/debug/java/com/flipperdevices/analytics/shake2report/Shake2Report.kt
components/analytics/shake2report/src/debug/java/com/flipperdevices/analytics/shake2report/listener/FlipperShakeDetector.kt

**Background**
Now you can shake via `adb shell am broadcast -a com.flipperdevices.SHAKE_ACTION`
**Changes**
- Add delegate for shake to report

Add Shake 2 report via adb

---

components/analytics/shake2report/src/debug/java/com/flipperdevices/analytics/shake2report/activity/Shake2ReportActivity.kt
components/analytics/shake2report/src/debug/java/com/flipperdevices/analytics/shake2report/helper/Shake2ReportDialog.kt
components/analytics/shake2report/src/debug/res/layout/dialog_edittext.xml
components/analytics/shake2report/src/debug/res/values/strings.xml

**Background**
Sometimes we need specify additional text in bug report
**Changes**
- Add edit text field in shake 2 report dialog

Add shake2report message field

---

components/core/ui/src/main/java/com/flipperdevices/core/ui/AndroidLifecycleViewModel.kt
components/pair/impl/src/main/java/com/flipperdevices/pair/impl/findstandart/service/PairDeviceViewModel.kt
components/pair/impl/src/main/java/com/flipperdevices/pair/impl/fragments/findcompanion/CompanionFindFragment.kt
components/pair/impl/src/main/res/values/strings.xml

**Background**
- We crash when pairing unsuccessful
- Not showing error state
**Changes**
- Show finding on onResume only on intialize state
- Show error if we can't connect to device

Not crash while we can't connect to device

---

components/bridge/api/src/main/java/com/flipperdevices/bridge/api/utils/Constants.kt
components/bridge/service/impl/src/main/java/com/flipperdevices/bridge/service/impl/FlipperService.kt
components/bridge/service/impl/src/main/java/com/flipperdevices/bridge/service/impl/delegate/FlipperServiceConnectDelegate.kt
components/bridge/service/impl/src/main/java/com/flipperdevices/bridge/service/impl/provider/FlipperServiceProviderImpl.kt
components/bridge/service/impl/src/main/java/com/flipperdevices/bridge/service/impl/provider/lifecycle/FlipperServiceConnectionHelperImpl.kt
components/core/log/src/main/java/com/flipperdevices/core/log/LogTagProvider.kt
components/pair/impl/src/main/java/com/flipperdevices/pair/impl/fragments/findcompanion/CompanionFindFragment.kt

**Changes**
- Fix twice stop service
- Fix when service not close long time
- Fix when service not registered

Fix some bugs

---

components/bridge/dao/src/main/java/com/flipperdevices/bridge/dao/FlipperFileFormat.kt
components/filemanager/impl/build.gradle.kts
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/composable/ComposableFileManager.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/composable/ComposableFileManagerSave.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/composable/ComposableFileManagerWithDialog.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/model/FileItem.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/model/FileManagerState.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/viewmodels/FileManagerViewModel.kt
components/filemanager/impl/src/main/res/values/strings.xml

**Background**
After implementing import in flipper app we want improve file manager
**Changes**
- Add progress bar
- Add icon to files
- Add "Empty folder" text
**Test plan**
- Open file manager

Add icon to file manager and progress bar

---

components/bottombar/impl/build.gradle.kts
components/bottombar/impl/src/main/java/com/flipperdevices/bottombar/impl/main/BottomNavigationFragment.kt
components/bottombar/impl/src/main/java/com/flipperdevices/bottombar/impl/navigate/ScreenTabProviderImpl.kt
components/info/impl/build.gradle.kts
components/info/impl/src/main/java/com/flipperdevices/info/impl/main/InfoFragment.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/main/compose/ComposeInfoScreen.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/main/model/DeviceSubScreen.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/main/viewmodel/InfoViewModel.kt
components/info/impl/src/main/res/values/strings.xml

**Background**
Now we have some tabs, filled with unrelevant content (like screenstreaming in settings)
**Changes**
- Move screens to Info tab

Move screen streaming and file manager to info screen

---

components/bottombar/api/src/main/java/com/flipperdevices/bottombar/api/BottomNavigationApi.kt
components/bottombar/impl/src/main/java/com/flipperdevices/bottombar/impl/api/BottomNavigationApiImpl.kt
components/bottombar/impl/src/main/java/com/flipperdevices/bottombar/impl/main/BottomNavigationFragment.kt
components/bottombar/impl/src/main/java/com/flipperdevices/bottombar/impl/main/TabContainerFragment.kt
components/bottombar/impl/src/main/java/com/flipperdevices/bottombar/impl/main/service/BottomNavigationViewModel.kt
components/bottombar/impl/src/main/java/com/flipperdevices/bottombar/impl/main/subnavigation/OnDoublePressOnTab.kt
components/core/navigation/src/main/java/com/flipperdevices/core/navigation/delegates/OnDoublePressOnTab.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/fragment/FileManagerSaveFragment.kt
components/screenstreaming/impl/src/main/java/com/flipperdevices/screenstreaming/impl/fragment/ScreenStreamingFragment.kt
components/singleactivity/impl/src/main/java/com/flipperdevices/singleactivity/impl/SingleActivity.kt

**Background**
I want behavior as on Youtube when i click on tab
**Changes**
- Add OnDoublePressOnTap
**Test plan**
Open any screen except main screen
Tap on tab again

Add double tap action

---

buildSrc/src/main/java/Dependencies.kt
components/bottombar/impl/build.gradle.kts
components/bottombar/impl/src/main/java/com/flipperdevices/bottombar/impl/main/compose/ComposeBottomBar.kt
components/bottombar/impl/src/main/java/com/flipperdevices/bottombar/impl/main/compose/ComposeMaterialYouTab.kt
components/bottombar/impl/src/main/res/values/colors.xml
components/core/ui/src/main/res/values/styles.xml
components/singleactivity/impl/build.gradle.kts
components/singleactivity/impl/src/main/AndroidManifest.xml

**Background**
Add bottombar to menu
**Changes**
- Add bottombar in material you styleguide

Add bottom bar

---

components/analytics/shake2report/impl/src/main/java/com/flipperdevices/analytics/shake2report/impl/listener/FlipperShakeDetector.kt

**Background**
Now when application in background we can shake bug
**Changes**
- Allow shake only when application in foreground
**Test plan**
- Exit from application
- shake
- Vibro shouldn't happens

When application close, not able to shake

---

buildSrc/src/main/java/Dependencies.kt
components/analytics/shake2report/impl/build.gradle.kts
components/analytics/shake2report/noop/build.gradle.kts
components/archive/impl/build.gradle.kts
components/bottombar/impl/build.gradle.kts
components/bridge/api/build.gradle.kts
components/bridge/impl/build.gradle.kts
components/bridge/provider/build.gradle.kts
components/bridge/service/api/build.gradle.kts
components/bridge/service/impl/build.gradle.kts
components/connection/impl/build.gradle.kts
components/core/navigation/build.gradle.kts
components/core/preference/build.gradle.kts
components/debug/impl/build.gradle.kts
components/deeplink/impl/build.gradle.kts
components/filemanager/api/build.gradle.kts
components/filemanager/impl/build.gradle.kts
components/info/impl/build.gradle.kts
components/pair/impl/build.gradle.kts
components/screenstreaming/impl/build.gradle.kts
components/share/api/build.gradle.kts
components/share/common/build.gradle.kts
components/share/export/build.gradle.kts
components/share/receive/build.gradle.kts
components/singleactivity/api/build.gradle.kts
components/singleactivity/impl/build.gradle.kts
gradle/libs.versions.toml
instances/app/build.gradle.kts

**Background**
Now we use hardcoded string for declare project dependencies
**Changes**
- Change project dependencies to variables in whole project
**Test plan**
Assemble it

Migrate to typesafe project deps

---

buildSrc/src/main/java/Dependencies.kt
components/analytics/shake2report/impl/build.gradle.kts
components/archive/impl/build.gradle.kts
components/archive/impl/src/main/java/com/flipperdevices/archive/impl/composable/page/ArchivePage.kt
components/archive/impl/src/main/java/com/flipperdevices/archive/impl/fragments/ArchiveFragment.kt
components/archive/impl/src/main/java/com/flipperdevices/archive/impl/viewmodel/TabViewModel.kt
components/archive/impl/src/main/res/values/strings.xml
components/bottombar/impl/build.gradle.kts
components/bridge/api/build.gradle.kts
components/bridge/dao/api/build.gradle.kts
components/bridge/impl/build.gradle.kts
components/bridge/service/impl/build.gradle.kts
components/bridge/synchronization/api/build.gradle.kts
components/bridge/synchronization/api/src/main/java/com/flipperdevices/bridge/synchronization/api/SynchronizationApi.kt
components/bridge/synchronization/api/src/main/java/com/flipperdevices/bridge/synchronization/api/SynchronizationState.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/SynchronizationTask.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/TmpSynchronization.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/api/SynchronizationApiImpl.kt
components/connection/impl/build.gradle.kts
components/connection/impl/src/main/java/com/flipperdevices/connection/impl/viewmodel/ConnectionStatusViewModel.kt
components/deeplink/impl/build.gradle.kts
components/filemanager/impl/build.gradle.kts
components/info/impl/build.gradle.kts
components/pair/impl/build.gradle.kts
components/screenstreaming/impl/build.gradle.kts
components/share/receive/build.gradle.kts
gradle/libs.versions.toml
instances/app/build.gradle.kts

**Background**
Now we have some light-weight features for synchronization
**Changes**
- Start synchronization just after open app
- Now synhcronization progress shown in connection bar
- Now show text if synchronization is stopped and keys not exist
- Add pull to refresh

Improve synchronization

---

components/archive/impl/src/main/java/com/flipperdevices/archive/impl/composable/ComposableArchive.kt
components/archive/impl/src/main/java/com/flipperdevices/archive/impl/composable/page/ArchivePage.kt
components/archive/impl/src/main/java/com/flipperdevices/archive/impl/composable/page/ComposablePager.kt
components/archive/impl/src/main/java/com/flipperdevices/archive/impl/composable/page/GeneralPage.kt
components/archive/impl/src/main/java/com/flipperdevices/archive/impl/composable/page/KeysList.kt
components/archive/impl/src/main/java/com/flipperdevices/archive/impl/composable/tab/ComposableTabs.kt
components/archive/impl/src/main/java/com/flipperdevices/archive/impl/di/ArchiveComponent.kt
components/archive/impl/src/main/java/com/flipperdevices/archive/impl/model/ArchiveTab.kt
components/archive/impl/src/main/java/com/flipperdevices/archive/impl/viewmodel/GeneralTabViewModel.kt
components/archive/impl/src/main/java/com/flipperdevices/archive/impl/viewmodel/TabViewModelFactory.kt
components/archive/impl/src/main/res/values/strings.xml
components/bridge/dao/api/src/main/java/com/flipperdevices/bridge/dao/api/DaoApi.kt
components/bridge/dao/api/src/main/java/com/flipperdevices/bridge/dao/api/delegates/FavoriteApi.kt
components/bridge/dao/api/src/main/java/com/flipperdevices/bridge/dao/api/delegates/KeyApi.kt
components/bridge/dao/impl/build.gradle.kts
components/bridge/dao/impl/schemas/com.flipperdevices.bridge.dao.impl.AppDatabase/1.json
components/bridge/dao/impl/schemas/com.flipperdevices.bridge.dao.impl.AppDatabase/2.json
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/AppDatabase.kt
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/api/DaoApiImpl.kt
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/api/delegates/FavoriteImpl.kt
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/api/delegates/KeyApiImpl.kt
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/model/FavoriteKey.kt
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/repository/FavoriteDao.kt
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/repository/KeyDao.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/SynchronizationTask.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/repository/FavoritesRepository.kt

**Background**
Now we have favorites in Flipper, but it's not synced with phone
**Changes**
- Add new flipper favorites table
- Add flipper tab in general page
- Fix bug with swipe refresh
**Test plan**
Add favorites on flipper
Start sync

Add favorites

---

components/debug/impl/src/main/java/com/flipperdevices/debug/impl/compose/ComposableDebugScreen.kt
components/debug/impl/src/main/java/com/flipperdevices/debug/impl/di/DebugComponent.kt
components/debug/impl/src/main/java/com/flipperdevices/debug/impl/fragments/DebugScreenFragment.kt
components/debug/impl/src/main/java/com/flipperdevices/debug/impl/viewmodel/DebugViewModel.kt

**Background**
Sometimes we lost our flipper and we want find it
**Changes**
- Add button in debug panel which send RPC request
**Test plan**
- Use build from https://github.com/flipperdevices/flipperzero-firmware/pull/937
- Press button

Add alarm button

---

components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/overflow/FlipperRequestStorageImpl.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/service/request/FlipperRequestApiImpl.kt
components/bridge/protobuf/proguard-rules.pro
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/SynchronizationTask.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/repository/HashRepository.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/repository/KeysListingRepository.kt

**Background**
Now we have some strange problems with synchronization
**Changes**
- Ignore protobuf objects for proguard optimization
- Add more logs in synchronization process

More verbose logging synchronization process

---

components/bridge/dao/api/src/main/java/com/flipperdevices/bridge/dao/api/delegates/FavoriteApi.kt
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/api/FavoriteImpl.kt
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/repository/FavoriteDao.kt
components/bridge/impl/build.gradle.kts
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/service/request/FlipperRequestApiImpl.kt
components/bridge/synchronization/impl/build.gradle.kts
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/SynchronizationTask.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/executor/DiffKeyExecutor.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/model/KeyDiff.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/model/KeyWithHash.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/model/ManifestFile.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/repository/FavoritesRepository.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/repository/ManifestRepository.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/repository/storage/ManifestStorage.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/utils/KeyDiffCombiner.kt
components/core/ktx/src/main/java/com/flipperdevices/core/ktx/jre/AtomicInt.kt

**Background**
We want add favorites in flipper app
**Changes**
- Add bidirectional synchronization
**Test plan**
- Add keys in favorites in flipper
- Run synchronization
- Check that keys exist

Improve synchronization for favorites

---

components/archive/impl/src/main/java/com/flipperdevices/archive/impl/viewmodel/GeneralTabViewModel.kt
components/bridge/dao/api/src/main/java/com/flipperdevices/bridge/dao/api/delegates/FavoriteApi.kt
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/api/FavoriteImpl.kt
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/repository/FavoriteDao.kt
components/connection/impl/src/main/res/values/strings.xml
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/ComposableKeyAction.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/ComposableKeyScreen.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/fragments/KeyScreenFragment.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/model/KeyScreenState.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/viewmodel/KeyScreenViewModel.kt
components/keyscreen/impl/src/main/res/drawable/ic_star_disabled.xml
components/keyscreen/impl/src/main/res/drawable/ic_star_enabled.xml
components/keyscreen/impl/src/main/res/values/colors.xml
components/keyscreen/impl/src/main/res/values/strings.xml

**Background**
Now we can synchronize between phone and flipper, but we can't add to favorites from phone
**Changes**
Add button "Add to favorite" in key screen
**Test plan**
Click to "Add to favorite"

Add favorite button to key screen

---

components/bridge/dao/api/src/main/java/com/flipperdevices/bridge/dao/api/model/parsed/FlipperKeyParsed.kt
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/api/KeyParserImpl.kt
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/api/parsers/IButtonParser.kt
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/api/parsers/InfraredParser.kt
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/api/parsers/KeyParserDelegate.kt
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/api/parsers/NFCParser.kt
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/api/parsers/SubGhzParser.kt
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/api/parsers/UnrecognizedParser.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/ComposableKeyCard.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/content/ComposableIButtonContent.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/content/ComposableInfraredContent.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/content/ComposableKeyContent.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/content/ComposableNFCContent.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/content/ComposableSubGhzContent.kt

**Background**
Now we support only RFID format
**Changes**
- Add support for irda, ibutton, nfc, subghz

Add more format support for key screen

---

components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/repository/FavoriteDao.kt
components/pair/impl/src/main/java/com/flipperdevices/pair/impl/composable/tos/ComposeTOS.kt
components/pair/impl/src/main/res/values/strings.xml

**Background**
Now we have joke in main screen
**Changes**
Change ToS and Privacy Policy warning to alpha warning
**Test plan**
Open first screen on clear application

Fix ToS screen

---

.github/workflows/internal.yml

**Background**
Now we publish incorrect version to github releases
**Changes**
Get minor version from jobs output

Fix version number in github releases

---

components/archive/impl/src/main/java/com/flipperdevices/archive/impl/composable/key/ComposableFlipperKey.kt
components/bottombar/impl/src/main/java/com/flipperdevices/bottombar/impl/main/compose/ComposeBottomBar.kt
components/core/ui/src/main/java/com/flipperdevices/core/ui/composable/ImageKtx.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/composable/searching/ComposablePermissionRequest.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/ComposableKeyCard.kt

**Background**
Now we have problem with vector icon
**Changes**
- Invalidate painter resource by key
**Test plan**
- Open permission screen
- Check that all icons shows correctly

Fix icons in permission screen

---

components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/composable/common/ComposableSearchingAppBar.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/composable/help/ComposableHelp.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/composable/help/ComposableHelpItem.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/composable/help/HelpOptions.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/composable/searching/ComposableSearching.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/fragments/DeviceSearchingFragment.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/fragments/HelpFragment.kt
components/firstpair/impl/src/main/res/values/strings.xml

**Background**
Add help screen
**Changes**
- Add help screen
**Test plan**
Open help screen

Add help screen

---

buildSrc/src/main/java/ApkConfig.kt
buildSrc/src/main/java/androidApplication.gradle.kts
buildSrc/src/main/java/commonAndroid.kt
components/share/export/build.gradle.kts

**Background**
Now we crash if we install release and debug in one time
**Changes**
- Now set application id  from buildSrc
- Suffix in application move to `ApkConfig`
**Test plan**
Install debug and release build on one phone

Fix install debug when release already installed

---

.github/workflows/internal.yml
.github/workflows/release_candidate.yml
buildSrc/build.gradle.kts
buildSrc/src/main/java/ApkConfig.kt
buildSrc/src/main/java/androidApplication.gradle.kts
buildSrc/src/main/java/commonAndroid.kt
components/analytics/shake2report/impl/src/main/java/com/flipperdevices/analytics/shake2report/impl/Shake2Report.kt
components/analytics/shake2report/impl/src/main/java/com/flipperdevices/analytics/shake2report/impl/activity/Shake2ReportActivity.kt
gradle/libs.versions.toml
sentry.properties

**Background**
Now we see obfuscated stacktrace:
**Changes**
- Add Sentry gradle plugin
- Add sentry auth token env in CI
**Test plan**
Shake crash in internal build and see how crash reported

Include sentry mapping upload in internal build

---

components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/SynchronizationTask.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/executor/AndroidKeyStorage.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/executor/DiffKeyExecutor.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/repository/ManifestRepository.kt

**Background**
Now we just ignore keys after first synchronization
**Changes**
- Fix typo in ManifestRepository
- Add more logs in synchronization
**Test plan**
- Synchronize keys
- Add one more key
- Synchronize again

Fix second synchronization

---

components/bridge/dao/api/src/main/java/com/flipperdevices/bridge/dao/api/model/FlipperKeyContent.kt
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/api/parsers/url/FFFUrlConstants.kt
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/api/parsers/url/FFFUrlDecoder.kt
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/api/parsers/url/FFFUrlEncoder.kt
components/deeplink/impl/src/main/AndroidManifest.xml
components/deeplink/impl/src/main/java/com/flipperdevices/deeplink/impl/parser/delegates/DeepLinkFlipperFormatSharing.kt

**Background**
Now we want handle intent from browser via scheme
**Changes**
- Support scheme for open link
**Test plan**
Go to https://codepen.io/lionzxy/pen/PoEwmwg
Try push on button

Handle deep link from chrome intent

---

components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/api/KeyApiImpl.kt

**Background**
Now we don't save notes on key add
**Changes**
Save note in database 
**Test plan**
Add key, edit notes, check notes

Fix notes saving

---

components/screenstreaming/impl/src/main/java/com/flipperdevices/screenstreaming/impl/composable/ButtonEnum.kt
components/screenstreaming/impl/src/main/java/com/flipperdevices/screenstreaming/impl/composable/ComposableControlButtons.kt
components/screenstreaming/impl/src/main/java/com/flipperdevices/screenstreaming/impl/composable/ComposableScreen.kt

**Background**
Now we have wrong layout on some devices
**Changes**
- Fix screen streaming layout
**Test plan**
Try open this screen on small phone

Fix screen streaming layout

---

components/bridge/dao/api/src/main/java/com/flipperdevices/bridge/dao/api/model/FlipperFileType.kt

**Background**
Now we have incorrect infrared folder in file type
**Changes**
Fix folder name from `irda` to `infrared`

Fix infrared folder

---

components/bridge/service/impl/src/main/java/com/flipperdevices/bridge/service/impl/FlipperService.kt
components/bridge/service/impl/src/main/java/com/flipperdevices/bridge/service/impl/FlipperServiceApiImpl.kt
components/bridge/service/impl/src/main/java/com/flipperdevices/bridge/service/impl/di/FlipperServiceComponent.kt
components/bridge/service/impl/src/main/java/com/flipperdevices/bridge/service/impl/provider/FlipperServiceProviderImpl.kt
components/bridge/service/impl/src/main/java/com/flipperdevices/bridge/service/impl/provider/lifecycle/FlipperServiceConnectionHelperImpl.kt
components/bridge/service/impl/src/test/java/com/flipperdevices/bridge/service/impl/provider/FlipperServiceProviderTest.kt
components/core/preference/src/main/proto/settings.proto

**Background**
Now we show foreground service
**Changes**
- Remove temporary foreground service and wrap it in settings

Remove background foreground service

---

components/bridge/dao/api/src/main/java/com/flipperdevices/bridge/dao/api/model/FlipperFileType.kt

**Background**
For now flipper types is incorrect
**Changes**
Correct flipper file types order

Reorder file type

---

components/archive/shared/src/main/java/com/flipperdevices/archive/shared/composable/ComposableKeyCard.kt
components/keyedit/impl/src/main/java/com/flipperdevices/keyedit/impl/viewmodel/KeyEditViewModel.kt
components/keyedit/impl/src/main/java/com/flipperdevices/keyedit/impl/viewmodel/LengthFilter.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/card/ComposableKeyCard.kt

**Background**
Now notes is nonselectable and on some screen looks incorrect
**Changes**
- Fix notes length limit
- Fix name length limit
- Make notes field is selectable in key screen
- Make notes field is selectable in key card in category screen
- Fit card if notes is empty

Improve notes

---

components/bottombar/impl/build.gradle.kts
components/bottombar/impl/src/main/java/com/flipperdevices/bottombar/impl/di/BottomBarComponent.kt
components/bottombar/impl/src/main/java/com/flipperdevices/bottombar/impl/main/BottomNavigationFragment.kt
components/bottombar/impl/src/main/java/com/flipperdevices/bottombar/impl/main/service/BottomNavigationViewModel.kt
components/core/preference/src/main/proto/settings.proto

**Background**
Now we just open archive tab each time
**Changes**
- Remember last opened tab
- Open device tab by default

Now we save latest open tab

---

components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/service/FlipperInformationApiImpl.kt
components/core/ui/src/main/res/values/colors.xml
components/info/impl/src/main/java/com/flipperdevices/info/impl/compose/bar/ComposableDeviceBar.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/compose/bar/ComposableFlipperBattery.kt
components/info/impl/src/main/res/values/colors.xml

**Background**
Now we don't show battery level
**Changes**
- Receive battery level from Flipper
- Fix color for battery level

Fix battery level layout

---

components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/actions/ComposableDelete.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/actions/ComposableFavorite.kt
components/keyscreen/impl/src/main/res/values/colors.xml
components/keyscreen/shared/src/main/java/com/flipperdevices/keyscreen/shared/bar/ComposableBarTitle.kt

**Background**
Now key screen have incorrect favorite color screen and incorrect title font size
**Changes**
- Fix font size for key screen title
- Fix favorite color

Fix colors and font size on key screen

---

components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/repository/FavoriteSynchronization.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/repository/flipper/FlipperFavoritesRepository.kt

**Background**
Now we remove keys from flipper if we don't understand it
**Changes**
- Don't remove keys from favorites.txt

Now we don't remove unrecognized keys from favorites

---

components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/FlipperBleManagerImpl.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/utils/BleKtx.kt
components/bridge/service/impl/src/main/java/com/flipperdevices/bridge/service/impl/FlipperServiceApiImpl.kt
components/core/preference/src/main/proto/settings.proto
components/settings/impl/src/main/java/com/flipperdevices/settings/impl/composable/category/DebugCategory.kt
components/settings/impl/src/main/java/com/flipperdevices/settings/impl/viewmodels/DebugViewModel.kt
components/settings/impl/src/main/res/values/strings.xml

**Background**
Now we have problem
https://forum.flipperzero.one/t/development-mode-feature/2159/2
**Changes**
- Add `ignore_unsupported_version`

Add ignore unsupported version tweak

---

components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/FlipperBleManagerImpl.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/overflow/FlipperSerialOverflowThrottler.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/service/BluetoothGattServiceWrapper.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/service/FlipperInformationApiImpl.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/service/request/FlipperRequestApiImpl.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/service/request/FlipperSerialApiImpl.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/service/requestservice/FlipperRpcInformationApiImpl.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/utils/BleKtx.kt

**Background**
Sometimes we crash with ANR if onReset or onService ready takes long time
**Changes**
Execute this method in single-thread dispatcher

Now reset and onDeviceReady happens in coroutines

---

CHANGELOG.md
components/archive/category/build.gradle.kts
components/archive/category/src/main/java/com/flipperdevices/archive/category/composable/ComposableCategory.kt
components/archive/category/src/main/java/com/flipperdevices/archive/category/composable/ComposableDeleted.kt
components/archive/category/src/main/java/com/flipperdevices/archive/category/di/CategoryComponent.kt
components/archive/category/src/main/java/com/flipperdevices/archive/category/fragments/CategoryFragment.kt
components/archive/category/src/main/java/com/flipperdevices/archive/category/fragments/DialogDeleteConfirmBuilder.kt
components/archive/category/src/main/java/com/flipperdevices/archive/category/viewmodels/DeleteViewModel.kt
components/archive/category/src/main/res/values/strings.xml
components/archive/search/src/main/java/com/flipperdevices/archive/search/composable/ComposableSearchContent.kt
components/archive/shared/src/main/java/com/flipperdevices/archive/shared/composable/ComposableAppBar.kt
components/archive/shared/src/main/java/com/flipperdevices/archive/shared/composable/ComposableKeyCard.kt
components/bridge/api/src/main/java/com/flipperdevices/bridge/api/manager/observers/ConnectionObserverComposite.kt
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/api/key/DeleteKeyApiImpl.kt
components/core/ui/src/main/java/com/flipperdevices/core/ui/composable/ComposableKeyType.kt

**Background**
Now we can restore key from key screen, but can't do it for "All" keys
**Changes**
- Add restore all button
- Add delete all button

Fix trash category

---

.github/workflows/pr.yml
CHANGELOG.md

**Background**
Sometimes i forgot add changelog lines
**Changes**
Fail PR checks if changelog.md not changed in this PR
**Test plan**
Try open PR without changing Changelog.md

Add changelog.md check

---

CHANGELOG.md
components/bridge/api/src/main/java/com/flipperdevices/bridge/api/manager/FlipperRequestApi.kt
components/bridge/api/src/main/java/com/flipperdevices/bridge/api/model/FlipperRequestPriority.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/overflow/FlipperRequestStorage.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/overflow/FlipperRequestStorageImpl.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/service/request/FlipperRequestApiImpl.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/executor/FlipperKeyStorage.kt
components/debug/stresstest/src/main/java/com/flipperdevices/debug/stresstest/viewmodel/StressTestViewModel.kt

**Background**
Now we can't cancel file upload 
**Changes**
- Remove all pending requests from RPC on cancel
- Send finish command on cancel
**Test plan**
Go to bruteforce and try cancel it

Add cancelation for file upload

---

CHANGELOG.md
components/bottombar/impl/src/main/java/com/flipperdevices/bottombar/impl/main/compose/ComposeBottomBar.kt
components/core/ui/src/main/res/values-v27/styles.xml

**Background**
Gray divider under Bottom Bar
**Changes**
* Setup divider to Nothing
**Test plan**
* Look to bottom bar

Remove divider under Bottom Bar

---

CHANGELOG.md
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/service/request/FlipperRequestApiImpl.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/compose/info/ComposableFirmwareVersionValueChoice.kt
components/info/shared/src/main/java/com/flipperdevices/info/shared/ComposableFirmwareVersion.kt
components/info/shared/src/main/res/values/strings.xml
components/updater/api/src/main/java/com/flipperdevices/updater/model/FirmwareChannel.kt
components/updater/downloader/src/main/java/com/flipperdevices/updater/downloader/model/FirmwareDirectoryListeningResponse.kt
components/updater/ui/src/main/java/com/flipperdevices/updater/ui/fragments/UpdaterFragment.kt

**Background**
Please, describe here why you create this PR
**Changes**
- [Fix concurrent exception in request api](https://github.com/flipperdevices/Flipper-Android-App/commit/759d10f18926206646387a7107c9491de0d47562)
- [Fix update selector](https://github.com/flipperdevices/Flipper-Android-App/commit/a4890eff0e382d8640476edfb361a8bb5dcca528)
- [Not sleep while update is active](https://github.com/flipperdevices/Flipper-Android-App/commit/f430601940778fc5f942eecf2113a719919dc263)

Small fixes for OTA updater

---

CHANGELOG.md
components/settings/impl/src/main/res/values/strings.xml

**Background**
The settings screen looked a bit clunky because of the wording of some labels there
**Changes**
Re-word a few strings so they sound a bit better
**Test plan**
Build the app, open the settings screen, look at the text there

Minor grammar corrections in the settings screen

---

CHANGELOG.md
components/core/ui/res/src/main/res/values-v23/styles.xml
components/info/impl/src/main/java/com/flipperdevices/info/impl/compose/info/ComposableFirmwareVersionValueChoice.kt
components/info/shared/src/main/java/com/flipperdevices/info/shared/ComposableFirmwareVersion.kt
components/info/shared/src/main/res/values/strings.xml

**Background**
Redesign menu for choose firmware channel 
**Changes**
* String resources for description
* Dim amount 0.15 
* Dialog menu
**Test plan**
* Click to firmware channel

Popup menu from choose firmware channel

---

CHANGELOG.md
components/core/preference/src/main/proto/settings.proto
components/updater/card/src/main/java/com/flipperdevices/updater/card/viewmodel/UpdateCardViewModel.kt

**Background**
Now we always open release channel
**Changes**
- Open channel which last time selected
**Test plan**
- Select channel
- Restart application
- Check channel choice

Save last open channel for updater

---

CHANGELOG.md
components/info/impl/src/main/java/com/flipperdevices/info/impl/compose/info/ComposableInfoCard.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/composable/ComposableUpdaterCard.kt

**Background**
Now we don't show placeholder when device connecting in update card and in device info card
**Changes**
Show progress when flipper connecting
**Test plan**
Try connect flipper

Add placeholders in info card and in updater card when device is connecting

---

CHANGELOG.md
components/updater/card/src/main/java/com/flipperdevices/updater/card/composable/ComposableFirmwareVersionValueChoice.kt

**Background**
* Ripple effect on choose firmware version
**Changes**
* Set null effect
**Test plan**

Remove ripple effect on dropdown menu

---

CHANGELOG.md
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/FlipperBleManagerImpl.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/PeripheralResponseReader.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/service/request/FlipperRequestApiImpl.kt
components/bridge/service/impl/build.gradle.kts
components/bridge/service/impl/src/main/java/com/flipperdevices/bridge/service/impl/FlipperServiceApiImpl.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/composable/ComposableUpdaterCard.kt

**Background**
Now we crash if some protobuf packet is invalid
**Changes**
Not crash if protobuf package invalid, just report to sentry

Not crash on invalid protobuf file

---

CHANGELOG.md
components/analytics/metric/api/src/main/java/com/flipperdevices/metric/api/events/complex/FlipperGattInfoEvent.kt
components/analytics/metric/api/src/main/java/com/flipperdevices/metric/api/events/complex/FlipperRPCInfoEvent.kt
components/analytics/metric/api/src/main/java/com/flipperdevices/metric/api/events/complex/SynchronizationEnd.kt
components/analytics/metric/api/src/main/java/com/flipperdevices/metric/api/events/complex/UpdateFlipperEnd.kt
components/analytics/metric/api/src/main/java/com/flipperdevices/metric/api/events/complex/UpdateFlipperStart.kt
components/analytics/metric/impl/build.gradle.kts
components/analytics/metric/impl/src/main/java/com/flipperdevices/metric/impl/api/MetricApiImpl.kt
components/analytics/metric/impl/src/main/java/com/flipperdevices/metric/impl/clickhouse/ClickhouseApi.kt
components/analytics/metric/impl/src/main/java/com/flipperdevices/metric/impl/clickhouse/ClickhouseApiImpl.kt
components/analytics/metric/impl/src/main/java/com/flipperdevices/metric/impl/countly/CountlyApi.kt
components/analytics/metric/impl/src/main/java/com/flipperdevices/metric/impl/countly/CountlyApiImpl.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/service/requestservice/FlipperRpcInformationApiImpl.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/SynchronizationTask.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/viewmodel/UpdateStateViewModel.kt
components/updater/downloader/build.gradle.kts
components/updater/downloader/src/main/java/com/flipperdevices/updater/downloader/api/DownloadAndUnpackDelegate.kt
components/updater/downloader/src/main/java/com/flipperdevices/updater/downloader/api/DownloaderApiImpl.kt
components/updater/downloader/src/main/java/com/flipperdevices/updater/downloader/di/KtorModule.kt
components/updater/impl/src/main/java/com/flipperdevices/updater/impl/api/UpdaterApiImpl.kt
gradle/libs.versions.toml

**Background**
Now we can't investigate metrics with mongodb
**Changes**
- Add support for clickhouse selfhosted server

Add clickhouse self hosted server

---

CHANGELOG.md
components/analytics/shake2report/impl/src/main/AndroidManifest.xml
components/deeplink/impl/src/main/AndroidManifest.xml
components/singleactivity/impl/src/main/AndroidManifest.xml
instances/app/src/main/AndroidManifest.xml

**Background**
* Use application only in portrait orientation
**Changes**
* Change activity parameter in manifests
**Test plan**

Setup screen orientation

---

CHANGELOG.md
components/bridge/api/src/main/java/com/flipperdevices/bridge/api/manager/service/FlipperVersionApi.kt
components/bridge/api/src/main/java/com/flipperdevices/bridge/api/model/FlipperVersionInformation.kt
components/bridge/api/src/main/java/com/flipperdevices/bridge/api/utils/Constants.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/service/FlipperVersionApiImpl.kt

**Background**
Now `0.10` less than `0.9`
**Changes**
Compare major and minor version separatly

Fix unsupported version comparison

---

CHANGELOG.md
components/core/ui/theme/src/main/kotlin/com/flipperdevices/core/ui/theme/FlipperTheme.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/composable/ComposableFirmwareUpdaterContent.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/composable/ComposableFirmwareUpdaterError.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/composable/ComposableFirmwareVersionValueChoice.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/composable/ComposableUpdateButton.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/composable/ComposableUpdaterCard.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/composable/ComposableUpdaterReboot.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/composable/dialogs/ComposableDialogUpdate.kt

**Background**
Refactor compose function for preview
**Changes**
* Compose function for updater card
* Preview function with FlipperTheme
* FlipperThemeInternal for testing
**Test plan**

Preview for updater card

---

CHANGELOG.md
components/updater/screen/src/main/java/com/flipperdevices/updater/screen/composable/ComposableUpdaterScreen.kt
components/updater/screen/src/main/java/com/flipperdevices/updater/screen/composable/ComposableUpdaterScreenPreview.kt
components/updater/screen/src/main/java/com/flipperdevices/updater/screen/fragments/UpdaterFragment.kt

**Background**
Preview updater screen
**Changes**
* Get color in fragment scope
* Preview function
**Test plan**

Preview updater screen

---

CHANGELOG.md
components/core/ktx/src/main/java/com/flipperdevices/core/ktx/jre/NumberKtx.kt
components/nfceditor/impl/build.gradle.kts
components/nfceditor/impl/src/main/java/com/flipperdevices/nfceditor/impl/composable/ComposableNfcCell.kt
components/nfceditor/impl/src/main/java/com/flipperdevices/nfceditor/impl/composable/ComposableNfcEditor.kt
components/nfceditor/impl/src/main/java/com/flipperdevices/nfceditor/impl/composable/ComposableNfcLine.kt
components/nfceditor/impl/src/main/java/com/flipperdevices/nfceditor/impl/composable/ComposableNfcSector.kt
components/nfceditor/impl/src/main/java/com/flipperdevices/nfceditor/impl/composable/ComposableScaleFactorCalculate.kt
components/nfceditor/impl/src/main/java/com/flipperdevices/nfceditor/impl/model/NfcEditorCursor.kt
components/nfceditor/impl/src/main/java/com/flipperdevices/nfceditor/impl/model/NfcEditorState.kt
components/nfceditor/impl/src/main/java/com/flipperdevices/nfceditor/impl/viewmodel/NfcEditorViewModel.kt
components/nfceditor/impl/src/main/java/com/flipperdevices/nfceditor/impl/viewmodel/TextUpdaterHelper.kt
components/nfceditor/impl/src/main/res/values/strings.xml
components/nfceditor/impl/src/test/kotlin/com/flipperdevices/nfceditor/impl/viewmodel/TextUpdaterHelperTest.kt

**Background**
Now we have huge lags with NFC editor. Also nfc editor not work correctly with text
**Changes**
- Optimize compose layout
- Add `TextUpdaterHelper`
**Test plan**
Try open sample on phone and try edit some cards

NFC Editor perfomance optimization

---

CHANGELOG.md
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/actions/ComposableEmulate.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/actions/ComposableSend.kt
components/nfceditor/impl/src/main/java/com/flipperdevices/nfceditor/impl/composable/ComposableNfcCell.kt
components/nfceditor/impl/src/main/java/com/flipperdevices/nfceditor/impl/composable/ComposableScaleFactorCalculate.kt
components/nfceditor/impl/src/main/java/com/flipperdevices/nfceditor/impl/viewmodel/NfcEditorStateProducerHelper.kt
components/nfceditor/impl/src/main/java/com/flipperdevices/nfceditor/impl/viewmodel/NfcEditorViewModel.kt

**Background**
Now we crush if key not synced and then launch emulate
**Changes**
- Disable emulate if key not synced
**Test plan**
Try edit name for key and then try press to emulate

Now handle case with disabled emulate

---

CHANGELOG.md
gradle.properties

**Background**
Now we execute configuration and build every time
**Changes**
- Not execute configuration/build if item already exist
**Test plan**
Try build gradle

Add gradle cache

---

CHANGELOG.md
buildSrc/src/main/java/ApkConfig.kt
components/keyscreen/impl/build.gradle.kts
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/actions/ComposableEmulate.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/actions/ComposableSend.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/di/KeyScreenComponent.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/viewmodel/EmulateViewModel.kt
gradle/libs.versions.toml
instances/app/build.gradle.kts
instances/app/src/main/java/com/flipperdevices/app/FlipperApplication.kt

**Background**
Now we try close app which emulate each time when we close key
**Changes**
- Add tangle to project
- Migrate to `EmulateViewModel` to tangle
- Execute close app on flipper only if app opened
**Test plan**
Try close key without active emulating and see that we don't try close app on flipper

Close emulate only if emulate active

---

CHANGELOG.md
components/core/ktx/src/main/java/com/flipperdevices/core/ktx/jre/BoundedInputStream.kt
components/core/ktx/src/main/java/com/flipperdevices/core/ktx/jre/FileKtx.kt
components/core/preference/src/main/java/com/flipperdevices/core/preference/FlipperStorageProvider.kt
components/core/ui/theme/src/main/kotlin/com/flipperdevices/core/ui/theme/models/FlipperPallet.kt
components/filemanager/api/src/main/java/com/flipperdevices/filemanager/api/navigation/FileManagerEntry.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/api/FileManagerEntryImpl.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/composable/ComposableFileManagerDownloadScreen.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/composable/ComposableFileManagerEditorScreen.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/composable/ComposableFileManagerScreen.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/composable/ComposableFileManagerUploadedScreen.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/composable/bar/ComposableEditorTopBar.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/composable/bar/ComposableFileManagerTopBar.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/composable/dialog/ComposableProgressDialog.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/composable/dialog/ComposableSelectDialog.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/model/EditorState.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/model/FileItem.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/viewmodels/EditorViewModel.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/viewmodels/ReceiveViewModel.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/viewmodels/ShareViewModel.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/viewmodels/helpers/DownloadFileHelper.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/viewmodels/helpers/UploadFileHelper.kt
components/filemanager/impl/src/main/res/values/strings.xml

**Background**
For now we can only download and share file, not edit
**Changes**
- Add ability edit files
**Test plan**
Try open text files and select edit

Add editor to file manager

---

CHANGELOG.md
components/bridge/api/src/main/java/com/flipperdevices/bridge/api/utils/FlipperSymbolFilter.kt
components/core/ui/res/src/main/res/drawable/ic_plus.xml
components/core/ui/theme/src/main/kotlin/com/flipperdevices/core/ui/theme/models/FlipperPallet.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/composable/ComposableFileManagerEditorScreen.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/composable/ComposableFileManagerScreen.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/composable/bar/ComposableFileManagerTopBar.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/composable/dialog/ComposableInputDialog.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/model/CreateFileManagerAction.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/viewmodels/FileManagerViewModel.kt
components/filemanager/impl/src/main/res/values/strings.xml
gradle.properties

**Background**
Now we can edit, download and upload file
**Changes**
- Add ability to create file
**Test plan**
Try create file

Add ability to create file from file manager

---

CHANGELOG.md
components/core/ktx/src/main/java/com/flipperdevices/core/ktx/jre/CoroutineLogKtx.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/tasks/CloseEmulateAppTask.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/tasks/CloseEmulateAppTaskHolder.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/viewmodel/EmulateViewModel.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/viewmodel/helpers/EmulateHelper.kt

**Background**
For now, sometimes we execute commands for start in incorrect order
**Changes**
- Use global mutex for respect order in all app
**Test plan**
Try click fast on start/stop emulate

Respect emulate order

---

CHANGELOG.md
components/updater/api/src/main/java/com/flipperdevices/updater/model/UpdateCardState.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/composable/ComposableFirmwareUpdaterContent.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/composable/ComposableUpdateButton.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/composable/ComposableUpdaterCard.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/viewmodel/UpdateCardViewModel.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/viewmodel/UpdateRequestViewModel.kt

**Background**
In updater screen we can't see changelog
**Changes**
* In UpdateStateAvailable add changelog - replace DistrubFile/FirmwareVersion to VersionFile(where DistrubFile/FirmwareVersion  + changelog)
* Fix preview states
**Test plan**
Try update

Fix when changeling not display in updater screen

---

CHANGELOG.md
components/updater/card/src/main/res/values/strings.xml

**Background**
Change text on updater flipper status
**Changes**
Change string resources
**Test plan**
Try update flipper and see updater status

Change text on updater flipper status

---

CHANGELOG.md
components/updater/screen/src/main/java/com/flipperdevices/updater/screen/composable/ComposableChangelog.kt

**Background**
Changelog scroll
**Changes**
Extension function with draw rectangle
**Test plan**
Update firmware and scroll column

Changelog scroll

---

CHANGELOG.md
components/core/ui/theme/src/main/kotlin/com/flipperdevices/core/ui/theme/FlipperTheme.kt
components/core/ui/theme/src/main/kotlin/com/flipperdevices/core/ui/theme/models/FlipperPallet.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/composable/ComposableFirmwareVersionValueChoice.kt

**Background**
Notification card both in light/dark theme
Padding in fm choose not completed
**Changes**
* Add color to dark theme
* Delete end padding
**Test plan**

Bugfix: notification card and padding in fw version

---

CHANGELOG.md
components/updater/card/build.gradle.kts
components/updater/card/src/main/java/com/flipperdevices/updater/card/viewmodel/UpdateCardViewModel.kt

**Background**
qFlipper offer update if assets not exist
We now we can also
**Changes**
Request md5 manifest file
**Test plan**
Try delete manifest file and reopen application

Offer update, if assets not exit on Flipper

---

CHANGELOG.md
components/share/receive/src/main/java/com/flipperdevices/share/receive/api/ArchiveKeyDeeplinkHandlerImpl.kt
components/share/receive/src/main/java/com/flipperdevices/share/receive/viewmodels/FlipperKeyParserHelper.kt
components/share/receive/src/main/java/com/flipperdevices/share/receive/viewmodels/KeyReceiveViewModel.kt

**Background**
Now we can open file manager and click to flipper file format(nfc, rfid etc)
**Changes**
* Support DeeplinkContent.InternalStorageFile in start activity
* KeyFlipperParser for InternalStorageFile or FFFContent
**Test plan**
Open file manager, choose flipper file format(nfc, rfid etc) and try see application open key import

Upload key-file from archive 

---

components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/SynchronizationTask.kt

**Background**
Found a possible copy-paste issue while checking the code
**Changes**
Fixed wrong enum used
**Test plan**
I don't know, code just makes sense

Fix wrong counter when reporting iButton sync end

---

CHANGELOG.md
components/archive/shared/build.gradle.kts
components/archive/shared/src/test/kotlin/com/flipperdevices/archive/shared/ExtractKeyMetaInformationTest.kt
components/core/ui/theme/src/main/kotlin/com/flipperdevices/core/ui/theme/models/FlipperPallet.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/composable/dialogs/ComposableDialogUpdate.kt
components/updater/screen/src/main/res/values/strings.xml

**Background**
**Changes**
* Change color for dialog title and firmware channel
* remove `the` on updater screen
* Test for ExtractKeyMetaInformation
**Test plan**
Try update

Redesign dialog after update

---

CHANGELOG.md
components/archive/impl/src/main/java/com/flipperdevices/archive/impl/composable/key/ComposableKeySmall.kt
components/archive/impl/src/main/java/com/flipperdevices/archive/impl/viewmodel/KeyItemViewModel.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/composable/dialogs/ComposableUpdateRequest.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/viewmodel/UpdateRequestViewModel.kt
components/updater/card/src/test/kotlin/com/flipperdevices/updater/card/viewmodel/UpdateRequestViewModelTest.kt

**Background**
Now bottom bar display if we navigation from archive
**Changes**
* Navigate to key screen by Global Cicerone
* Test for UpdateRequestCard 🌚 and refactor by tangle
**Test plan**
Open application -> Arhcive -> Choose key; and see no bottom bar

Don`t display bottom bar on key screen after navigation from archive

---

components/updater/impl/src/main/java/com/flipperdevices/updater/impl/UpdaterTask.kt

**Background**
Please, describe here why you create this PR
**Changes**
Here what change in this PR..
**Test plan**

fix import

---

CHANGELOG.md
components/updater/screen/src/main/java/com/flipperdevices/updater/screen/composable/ComposableUpdateFailedContent.kt
gradle/libs.versions.toml

**Background**
Revert feature for center content in markdown
**Changes**
* Bump markdown version
**Test plan**

Revert compose center

---

metadata/en-US/full_description.txt

**Background**
Reading through all documentation for spelling, grammar, and punctuation errors.
**Changes**
Updated minor punctuation errors.
**Test plan**
No testing needed.

Updated full_description.txt

---

.github/changelog/whatsnew-en-US

**Background**
Looking through all documentation for spelling, grammar, and punctuation errors.
**Changes**
Fixed minor spelling, grammar, and punctuation errors.
**Test plan**
There is no need to test this fix.

Updated whatsnew-en-US

---

.github/ISSUE_TEMPLATE/need-help.md

**Background**
Looking through all documentation for spelling, grammar, and punctuation errors.
**Changes**
Fixed minor grammatical errors.
**Test plan**
There is no need to test this fix.

Updated need-help.md

---

.github/ISSUE_TEMPLATE/in-progress.md

**Background**
Looking through all documentation for spelling, grammar, and punctuation errors.
**Changes**
Fixed minor grammatical error.
**Test plan**
There is no need to test this fix.

Updated in-progress.md

---

CHANGELOG.md
components/bridge/dao/api/src/main/java/com/flipperdevices/bridge/dao/api/model/parsed/FlipperKeyParsed.kt
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/api/parsers/SubGhzParser.kt
components/core/ktx/src/main/java/com/flipperdevices/core/ktx/jre/TimeHelper.kt
components/keyscreen/emulate/build.gradle.kts
components/keyscreen/emulate/src/main/java/com/flipperdevices/keyscreen/emulate/composable/ComposableSimpleEmulateButton.kt
components/keyscreen/emulate/src/main/java/com/flipperdevices/keyscreen/emulate/composable/ComposableSubGhzSendButton.kt
components/keyscreen/emulate/src/main/java/com/flipperdevices/keyscreen/emulate/composable/common/button/ComposableEmulateButtonPreview.kt
components/keyscreen/emulate/src/main/java/com/flipperdevices/keyscreen/emulate/composable/common/button/sweep/GetEmulateProgressBrush.kt
components/keyscreen/emulate/src/main/java/com/flipperdevices/keyscreen/emulate/model/EmulateProgress.kt
components/keyscreen/emulate/src/main/java/com/flipperdevices/keyscreen/emulate/tasks/CloseEmulateAppTask.kt
components/keyscreen/emulate/src/main/java/com/flipperdevices/keyscreen/emulate/viewmodel/EmulateViewModel.kt
components/keyscreen/emulate/src/main/java/com/flipperdevices/keyscreen/emulate/viewmodel/SimpleEmulateViewModel.kt
components/keyscreen/emulate/src/main/java/com/flipperdevices/keyscreen/emulate/viewmodel/SubGhzViewModel.kt
components/keyscreen/emulate/src/main/java/com/flipperdevices/keyscreen/emulate/viewmodel/helpers/EmulateHelper.kt
components/keyscreen/emulate/src/test/kotlin/com/flipperdevices/keyscreen/emulate/viewmodel/helpers/EmulateHelperTest.kt

**Background**
For now we emulate subghz fully at least once
**Changes**
- Calculate emulate time for subghz
- Add new logic for emulate subghz
**Test plan**
Try press on send/emulate button

New emulate logic

---

CHANGELOG.md
components/info/impl/build.gradle.kts
components/info/impl/src/main/java/com/flipperdevices/info/impl/compose/elements/ComposableInfoCardContent.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/compose/screens/ComposableFullDeviceInfoScreen.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/compose/screens/fullinfo/ComposableDeviceFullInfo.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/compose/screens/fullinfo/ComposableFirmwareInfo.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/model/DeviceInfo.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/viewmodel/DeviceInfoViewModel.kt
components/info/impl/src/test/kotlin/com/flipperdevices/info/impl/model/DeviceInfoTest.kt
components/info/shared/src/main/java/com/flipperdevices/info/shared/ComposableDeviceInfoRow.kt
config/geminio/modules_templates/Blank Module/recipe.yaml
config/geminio/modules_templates/Blank Module/root/build.gradle.kts.ftl

**Background**
Change text color in info stat when storage(int/ext) ending
**Changes**
* Geminio config update for test
* Changes color text in info
* DeviceInfo method for check less 20Kb + TESTS🌚
* Fix get color from branch, not commit(fun getFirmwareChannel(commit: String?): FirmwareChannel?)
**Test plan**
Try install doom

Warning when storage ending

---

CHANGELOG.md
components/info/impl/src/main/java/com/flipperdevices/info/impl/model/DeviceInfo.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/viewmodel/FullInfoViewModel.kt

**Background**
Fix display storage info
**Changes**
Rewrite toString
**Test plan**
Try share full device info

Fix display storage info

---

CHANGELOG.md
components/core/ui/theme/src/main/kotlin/com/flipperdevices/core/ui/theme/FlipperTheme.kt
components/core/ui/theme/src/main/kotlin/com/flipperdevices/core/ui/theme/composable/FlipperPalletProvider.kt

**Background**
Now we choose theme by flag isLight
**Changes**
Method with when for new theme
**Test plan**

Flipper Pallet by theme in android application

---

CHANGELOG.md
components/updater/impl/src/main/java/com/flipperdevices/updater/impl/UpdaterTask.kt

**Background**
Duplicate folder for release and rc builds
Short name get from folder, not url
**Changes**
Get internal folder name
**Test plan**
Upload to flipper rc build
Upload to flipper release build
Check what diff folder on flipper

Fix name of updater folder

---

CHANGELOG.md
components/updater/downloader/src/main/java/com/flipperdevices/updater/downloader/api/DownloaderApiImpl.kt
components/updater/impl/src/main/java/com/flipperdevices/updater/impl/UpdaterTask.kt

**Background**
Now, if firmware not exist on server(or some trouble with server) we have total bytes -1
**Changes**
Check what total bytes not less 0
**Test plan**

Unknown percent on error update

---

components/updater/downloader/src/main/java/com/flipperdevices/updater/downloader/api/DownloaderApiImpl.kt

Fix condition for throw

---

CHANGELOG.md
components/core/ktx/src/main/java/com/flipperdevices/core/ktx/jre/NumberKtx.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/model/DeviceInfo.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/model/StorageStateFormatter.kt
components/info/impl/src/test/kotlin/com/flipperdevices/info/impl/helper/StorageStateFormatterTest.kt

**Background**
Storage Stats formatter by kibibyte
**Changes**
* Custom formatter and test
**Test plan**
Start app and see storage stats in Device Info

Storage Stats formatter by kibibyte

---

CHANGELOG.md
components/bridge/api/build.gradle.kts
components/bridge/api/src/main/java/com/flipperdevices/bridge/api/utils/FlipperSymbolFilter.kt
components/bridge/api/src/test/kotlin/com/flipperdevices/bridge/api/utils/FlipperSymbolFilterTest.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/composable/dialog/ComposableInputDialog.kt
components/keyedit/impl/src/main/java/com/flipperdevices/keyedit/impl/composable/FlipperTextField.kt
components/keyedit/impl/src/main/res/values/strings.xml

**Background**
Allow whitespace in key name
**Changes**
* Test to filter letters
* Change capitalization for upper first letter
**Test plan**
Green pipeline
Try edit key name with whitespace

Allow whitespace in key name

---

CHANGELOG.md
components/bridge/api/src/main/java/com/flipperdevices/bridge/api/model/FlipperRequest.kt
components/core/ktx/src/main/java/com/flipperdevices/core/ktx/jre/TimeHelper.kt
components/core/preference/src/main/proto/settings.proto
components/updater/card/src/main/java/com/flipperdevices/updater/card/helpers/delegates/UpdateOfferRegionChange.kt
components/updater/card/src/test/kotlin/com/flipperdevices/updater/card/helpers/delegates/UpdateOfferRegionChangeTest.kt
components/updater/subghz/src/main/kotlin/com/flipperdevices/updater/subghz/helpers/SubGhzProvisioningHelper.kt

**Background**
Get last region from flipper and compare with current on phone
**Changes**
Get file .region_data and take country code
**Test plan**
Green pipeline

Get last region from flipper

---

CHANGELOG.md
components/core/ktx/src/main/java/com/flipperdevices/core/ktx/jre/NumberKtx.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/model/StorageStateFormatter.kt
components/info/impl/src/test/kotlin/com/flipperdevices/info/impl/helper/StorageStateFormatterTest.kt

**Background**
Formatter convert bytes to string
**Changes**
* Convert any number to string by formatter
* Format 0.0(#)
**Test plan**
Green pipeline

Formatter convert bytes to string

---

CHANGELOG.md
components/deeplink/api/src/main/java/com/flipperdevices/deeplink/model/Deeplink.kt
components/deeplink/impl/src/main/AndroidManifest.xml
components/deeplink/impl/src/main/java/com/flipperdevices/deeplink/impl/parser/delegates/DeepLinkWebUpdater.kt
components/updater/api/build.gradle.kts
components/updater/api/src/main/java/com/flipperdevices/updater/api/UpdateDeeplinkHandler.kt
components/updater/api/src/main/java/com/flipperdevices/updater/model/UpdateRequest.kt
components/updater/screen/src/main/java/com/flipperdevices/updater/screen/api/UpdateDeeplinkHandlerImpl.kt

**Background**
Update from web updater
**Changes**
* Deeplink for parse query (Not use FFFDecoder because that user fragment from uri)
* Deeplink handler navigate to updater screen 
**Test plan**

Update from web updater

---

CHANGELOG.md
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/composable/ComposableFileManagerScreen.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/composable/bar/ComposableFileManagerTopBar.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/viewmodels/FileManagerViewModel.kt
components/filemanager/impl/src/main/res/values/strings.xml

**Background**
Right now we cannot delete files from the file manager
**Changes**
- Added item to the dialog - delete
**Test plan**
Try delete file by file manager

Add delete action in filemanager

---

CHANGELOG.md
components/screenstreaming/impl/src/main/java/com/flipperdevices/screenstreaming/impl/api/ScreenStreamingFeatureEntryImpl.kt

**Background**
Screen streaming stop working
**Changes**
Function no realization
**Test plan**

Screen streaming broke

---

components/nfc/attack/impl/src/main/res/values/strings.xml
components/nfc/mfkey32/screen/src/main/res/values/strings.xml

**Background**
I've changed title for Mfkey32 for more consistency
**Changes**
- Update title in Mfkey32 Tab
- Update title in Navigation Bar

Update title for Mfkey32 in NFC Tools screen

---

CHANGELOG.md
components/nfc/mfkey32/screen/build.gradle.kts
components/nfc/mfkey32/screen/src/main/java/com/flipperdevices/nfc/mfkey32/screen/composable/progressbar/ComposableMfKey32NotFound.kt
components/nfc/mfkey32/screen/src/main/java/com/flipperdevices/nfc/mfkey32/screen/viewmodel/FlipperColorViewModel.kt

**Background**
Right now we don't show black flipper on black flipper
**Changes**
Respect color of flipper

Flipper color on error screen

---

CHANGELOG.md
components/nfc/mfkey32/screen/build.gradle.kts
components/nfc/mfkey32/screen/src/main/java/com/flipperdevices/nfc/mfkey32/screen/composable/ComposableMfKey32Screen.kt
components/nfc/mfkey32/screen/src/main/res/values/strings.xml

**Background**
On button back dispose dialog about abort tool
**Changes**
* string res
* multichoose dialog
**Test plan**
* start mfkey32 tools
* click button back on AppBar and see dialog with some messages

Button back dialog on mfkey32 screen

---

CHANGELOG.md
components/nfc/mfkey32/screen/src/main/java/com/flipperdevices/nfc/mfkey32/screen/composable/progressbar/error/ComposableMfKey32ReadWrite.kt
components/nfceditor/impl/src/main/java/com/flipperdevices/nfceditor/impl/composable/ComposableNfcCell.kt
components/nfceditor/impl/src/main/java/com/flipperdevices/nfceditor/impl/composable/card/ComposableAdditionalInfoCard.kt
components/nfceditor/impl/src/main/java/com/flipperdevices/nfceditor/impl/model/NfcEditorState.kt
components/share/receive/src/main/java/com/flipperdevices/share/receive/fragments/KeyReceiveFragment.kt

**Background**
Now we have dynamic color on card
**Changes**
* Change cell type for additional info
* So set static color for that type
**Test plan**
Change devices theme and see no changes color on metadata

Display by white color on NFC card

---

CHANGELOG.md
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/api/KeyParserImpl.kt
components/bridge/dao/impl/src/main/java/com/flipperdevices/bridge/dao/impl/api/parsers/url/FFFUrlConstants.kt
components/share/uploader/src/main/kotlin/com/flipperdevices/uploader/compose/ComposableSheetContent.kt

**Background**
New format share link
**Changes**
* Parse id from fragment
**Test plan**
* Try share or import key

Change formatter share link

---

CHANGELOG.md
components/bridge/dao/api/src/main/java/com/flipperdevices/bridge/dao/api/model/FlipperKey.kt
components/share/uploader/src/main/kotlin/com/flipperdevices/uploader/viewmodel/UploaderViewModel.kt

**Background**
Now we share original NFC file
**Changes**
Check if shadow file exist on key
**Test plan**
Add shadow file to original key and change some data
Click share on original file and reimport file

Share shadow file if that exist on NFC

---

CHANGELOG.md
components/analytics/metric/api/src/main/java/com/flipperdevices/metric/api/events/SimpleEvent.kt
components/analytics/metric/impl/src/main/java/com/flipperdevices/metric/impl/clickhouse/ClickhouseApiImpl.kt
components/settings/impl/src/main/java/com/flipperdevices/settings/impl/viewmodels/ExperimentalViewModel.kt
components/share/uploader/build.gradle.kts
components/share/uploader/src/main/kotlin/com/flipperdevices/uploader/viewmodel/UploaderViewModel.kt

**Background**
New metric for share flow
**Changes**
* New simple event value
* Call metric in share flow
**Test plan**
Green pipeline

New metric for share flow

---

build-logic/settings.gradle.kts
settings.gradle.kts

[WIP] Add test repo

---

CHANGELOG.md
components/analytics/metric/impl/src/main/java/com/flipperdevices/metric/impl/clickhouse/ClickhouseApiImpl.kt

**Background**
Right now we have a problem with local build
**Changes**
Rename shared repo filename to shared name
**Test plan**
Try build application

Fix local build

---

CHANGELOG.md
components/core/ui/ktx/src/main/java/com/flipperdevices/core/ui/ktx/ComposableFlipperButton.kt
components/core/ui/ktx/src/main/java/com/flipperdevices/core/ui/ktx/ComposableKeyType.kt
components/core/ui/ktx/src/main/java/com/flipperdevices/core/ui/ktx/PlaceholderConnectingktx.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/card/ComposableKeyCard.kt
components/keyscreen/shared/build.gradle.kts
components/keyscreen/shared/src/main/java/com/flipperdevices/keyscreen/shared/content/ComposableKeyContent.kt
components/share/receive/src/main/java/com/flipperdevices/share/receive/composable/ComposableKeyReceive.kt
components/share/receive/src/main/java/com/flipperdevices/share/receive/composable/component/ComposableKeySaveFooter.kt
components/share/receive/src/main/java/com/flipperdevices/share/receive/composable/screen/ComposableKeyProgressScreen.kt
components/share/receive/src/main/java/com/flipperdevices/share/receive/composable/screen/ComposableKeySaveScreen.kt
components/share/receive/src/main/res/values/strings.xml

**Background**
Shimmers on key content
**Changes**
* Composition Local flags for shimmer
* Custom modifer for shimmer
* Remove edit button
**Test plan**
Open key by link and wait for loading

Key loading view on receive view

---

.github/workflows/gradle-wrapper-validation.yml
.github/workflows/internal.yml
.github/workflows/pr.yml
.github/workflows/pr_gradle.yml
.github/workflows/release.yml
.github/workflows/release_candidate.yml

**Background**
FL-2901
**Changes**
Remove deprecated actions
Fix style
**Test plan**
All workflows should work as before

[FL-2901] CI/CD improovements

---

.github/workflows/internal.yml
.github/workflows/release.yml

**Background**
Previous PR broke internal.yml
**Changes**
upload-google-play version rollback
**Test plan**
internal.yml should work

upload-google-play rollback

---

README.md

Hi,
This small PR adds two buttons to get your app on F-Droid and Google Play, and a link to get your app from the Releases Section 👍 
You can now eventually add the [fdroid](https://github.com/topics/fdroid) and/or [f-droid](https://github.com/topics/f-droid) tags that will appear on the right side of the repo.
close #46

Update README.md with download links

---

CHANGELOG.md

**Background**
Fix and features going to release 1.4.1
**Changes**
Replace str
**Test plan**
Green pipeline

Replace changes to version 1.4.1

---

components/core/ui/dialog/src/main/java/com/flipperdevices/core/ui/dialog/composable/multichoice/FlipperMultiChoiceDialogContent.kt

**Background**
Action on close multiselection dialog
**Changes**
Receive link on function
**Test plan**
Try close multiselection dialog by icon

Action on close multiselection dialog

---

.editorconfig
CHANGELOG.md
components/archive/category/src/main/java/com/flipperdevices/archive/category/composable/ComposableCategory.kt
components/archive/impl/src/main/java/com/flipperdevices/archive/impl/composable/ComposableArchive.kt
components/archive/search/src/main/java/com/flipperdevices/archive/search/composable/ComposableSearch.kt
components/archive/search/src/main/java/com/flipperdevices/archive/search/composable/ComposableSearchContent.kt
components/archive/shared/src/main/java/com/flipperdevices/archive/shared/composable/ComposableKeyCard.kt
components/bottombar/impl/src/main/java/com/flipperdevices/bottombar/impl/main/BottomNavigationFragment.kt
components/core/ui/fragment/src/main/java/com/flipperdevices/core/ui/fragment/ComposeFragment.kt
components/core/ui/hexkeyboard/src/main/kotlin/com/flipperdevices/core/ui/hexkeyboard/ComposableHexKeyboard.kt
components/core/ui/theme/src/main/kotlin/com/flipperdevices/core/ui/theme/FlipperTheme.kt
components/core/ui/theme/src/main/kotlin/com/flipperdevices/core/ui/theme/composable/FlipperPalletProvider.kt
components/faphub/main/impl/src/main/java/com/flipperdevices/main/impl/composable/ComposableFapHubMainScreen.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/composable/help/ComposableHelpItem.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/composable/searching/ComposableSearchingStatus.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/compose/bar/ComposableDeviceBar.kt
components/info/shared/src/main/java/com/flipperdevices/info/shared/ButtonElementCard.kt
components/keyscreen/emulate/src/main/java/com/flipperdevices/keyscreen/emulate/composable/common/ComposableHoldToSendInternal.kt
components/screenstreaming/impl/src/main/java/com/flipperdevices/screenstreaming/impl/composable/ComposableControlButtons.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/composable/ComposableFirmwareUpdaterError.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/composable/ComposableUpdaterCard.kt
components/updater/screen/src/main/java/com/flipperdevices/updater/screen/composable/ComposableChangelog.kt
components/updater/screen/src/main/java/com/flipperdevices/updater/screen/composable/ComposableUpdaterScreen.kt
components/updater/screen/src/main/java/com/flipperdevices/updater/screen/fragments/UpdaterFragment.kt
components/wearable/setup/impl/src/main/java/com/flipperdevices/wearable/setup/impl/composable/ComposableFindPhone.kt
components/wearable/sync/wear/impl/src/main/java/com/flipperdevices/wearable/sync/wear/impl/api/KeysListApiImpl.kt
components/wearable/sync/wear/impl/src/main/java/com/flipperdevices/wearable/sync/wear/impl/composable/ComposableKeysList.kt
config/detekt/detekt.yml

**Background**
Right now we have detekt in project, but it fails
**Changes**
- Fix all detekt errors except ComposableParamOrder and ModifierMissing
**Test plan**
CI pipeline is green

Detekt lint error Part 2

---

CHANGELOG.md
components/core/markdown/src/main/java/com/flipperdevices/core/markdown/ComposableMarkdown.kt
components/updater/screen/src/main/java/com/flipperdevices/updater/screen/composable/ComposableChangelog.kt
components/updater/screen/src/main/java/com/flipperdevices/updater/screen/helper/ChangelogFormatter.kt
gradle/libs.versions.toml

**Background**
New format markdown changelog
**Changes**
Formatter markdown
**Test plan**
Try update and see readable changelog

Format markdown changelog

---

CHANGELOG.md
components/bridge/service/impl/src/main/AndroidManifest.xml
components/keyedit/impl/src/main/java/com/flipperdevices/keyedit/impl/model/EditableKey.kt
components/updater/api/src/main/java/com/flipperdevices/updater/model/UpdateRequest.kt
components/updater/card/src/main/res/values/strings.xml
components/wearable/core/ui/ktx/src/main/java/com/flipperdevices/wearable/core/ui/ktx/RememberRipple.kt
components/widget/impl/src/main/res/layout/widget_layout_base.xml

**Background**
Fix android lint warning
**Changes**
* Parselize + Parcelable
* Notification permission
* Formated string
* Unuse ripple
* app:tint
**Test plan**
Green `gradle clean`

Fix android lint warning

---

CHANGELOG.md
components/archive/category/src/main/java/com/flipperdevices/archive/category/fragments/CategoryFragment.kt
components/archive/impl/src/main/java/com/flipperdevices/archive/impl/composable/ComposableArchive.kt
components/bottombar/impl/src/main/java/com/flipperdevices/bottombar/impl/main/BottomNavigationFragment.kt
components/bottombar/impl/src/main/java/com/flipperdevices/bottombar/impl/main/TabContainerFragment.kt
components/core/ktx/src/main/java/com/flipperdevices/core/ktx/android/BundleKtx.kt
components/core/ktx/src/main/java/com/flipperdevices/core/ktx/android/IntentKtx.kt
components/core/ui/hexkeyboard/src/main/kotlin/com/flipperdevices/core/ui/hexkeyboard/ImmutableEnumMap.kt
components/core/ui/ktx/src/main/java/com/flipperdevices/core/ui/ktx/OnHoldModifierKtx.kt
components/core/ui/ktx/src/main/java/com/flipperdevices/core/ui/ktx/SwipeRefresh.kt
components/faphub/category/impl/build.gradle.kts
components/faphub/category/impl/src/main/java/com/flipperdevices/faphub/category/impl/api/FapCategoryContentType.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/api/DeeplinkContentType.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/api/ShareFileType.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/composable/bar/ComposableEllipsizeStartText.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/composable/searching/ComposableSearchingDevices.kt
components/inappnotification/impl/src/main/java/com/flipperdevices/inappnotification/impl/composable/ComposableInAppNotificationCardContent.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/fragment/InfoFragment.kt
components/keyscreen/emulate/src/main/java/com/flipperdevices/keyscreen/emulate/viewmodel/SubGhzViewModel.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/fragments/KeyScreenFragment.kt
components/nfceditor/impl/src/main/java/com/flipperdevices/nfceditor/impl/fragments/NfcEditorFragment.kt
components/share/uploader/src/main/kotlin/com/flipperdevices/uploader/api/FlipperKeyPathType.kt
components/singleactivity/impl/src/main/java/com/flipperdevices/singleactivity/impl/SingleActivity.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/viewmodel/UpdateCardViewModel.kt
components/updater/screen/src/main/java/com/flipperdevices/updater/screen/fragments/UpdaterFragment.kt
components/updater/subghz/src/main/kotlin/com/flipperdevices/updater/subghz/helpers/RegionProvisioningHelper.kt
components/widget/screen/src/main/java/com/flipperdevices/widget/screen/compose/ComposableKeys.kt

**Background**
Build without warnings
**Changes**
* New parcelable/serializelable for tiramisu SDK
* awaitLongPressOrCancellation from new version android source
* Lottie animation progress by lambda
* Deprecation annotation on get local
* New SwipeRefreshe
**Test plan**
Green pipeline

Fix gradle warnings

---

CHANGELOG.md
components/core/ui/ktx/src/main/java/com/flipperdevices/core/ui/ktx/SwipeRefresh.kt
components/updater/screen/src/main/java/com/flipperdevices/updater/screen/helper/ChangelogFormatter.kt

**Background**
Format markdown changelog with clickable link and bold nickname
**Changes**
Markdown bold
**Test plan**
Try update and see nicknames

Format markdown changelog with clickable link and bold nickname

---

CHANGELOG.md
components/core/ui/ktx/src/main/java/com/flipperdevices/core/ui/ktx/SwipeRefresh.kt
components/share/cryptostorage/src/main/kotlin/com/flipperdevices/share/cryptostorage/helper/CryptoHelper.kt

**Background**
Key encryption without paddings
**Changes**
* Use encoder without padding
* Replace id/path in link
**Test plan**
Try generate share link on android and open on ios

Key encryption without paddings

---

CHANGELOG.md
components/keyscreen/emulate/src/main/java/com/flipperdevices/keyscreen/emulate/api/KeyEmulateApiImpl.kt

**Background**
No emulated in deleted key
**Changes**
Check if key exist
**Test plan**
Delete key and go to ths key in trash`

Remove emulated button on deleted screen 

---

CHANGELOG.md
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/repository/FolderKeySynchronization.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/repository/manifest/ManifestRepository.kt
components/bridge/synchronization/impl/src/test/java/com/flipperdevices/bridge/synchronization/impl/repository/manifest/ManifestRepositoryTest.kt

**Background**
We have a broken file synchronization because we check the file type
**Changes**
Now we check the folder instead of the type
**Test plan**
Try synchronize shadow file

Fix shadow file synchronization

---

components/updater/downloader/src/main/java/com/flipperdevices/updater/downloader/api/DownloaderApiImpl.kt

**Background**
Filter by f7 target
**Changes**
Condition for FW f7
**Test plan**
Update lasted dev

Filter downloaded FW by type and target

---

CHANGELOG.md
components/archive/search/src/main/java/com/flipperdevices/archive/search/api/SearchFeatureEntryImpl.kt
components/core/ui/navigation/src/main/java/com/flipperdevices/core/ui/navigation/FeatureScreenRootRoute.kt
components/core/ui/navigation/src/main/java/com/flipperdevices/core/ui/navigation/NavigationOnResultKtx.kt
components/widget/api/build.gradle.kts
components/widget/api/src/main/java/com/flipperdevices/widget/api/WidgetFeatureEntry.kt
components/widget/screen/build.gradle.kts
components/widget/screen/src/main/java/com/flipperdevices/widget/screen/api/WidgetFeatureEntryImpl.kt
components/widget/screen/src/main/java/com/flipperdevices/widget/screen/compose/WidgetNavigation.kt
components/widget/screen/src/main/java/com/flipperdevices/widget/screen/compose/WidgetOptionsComposable.kt
components/widget/screen/src/main/java/com/flipperdevices/widget/screen/fragments/WidgetSelectFragment.kt
components/widget/screen/src/main/java/com/flipperdevices/widget/screen/viewmodel/WidgetSelectViewModel.kt

**Background**
Process refactor navigation
**Changes**
* New feature entry
* OnResult in Compose
**Test plan**
* Add widget from archive screen
* Add widget by search

Compose navigation for widget flow

---

CHANGELOG.md
components/widget/api/src/main/java/com/flipperdevices/widget/api/WidgetFeatureEntry.kt
components/widget/screen/src/main/java/com/flipperdevices/widget/screen/api/WidgetFeatureEntryImpl.kt

**Background**
Widget by composable feature entry
**Changes**
* Composable feature entry
**Test plan**
Wait process deeplink

Widget by composable feature entry

---

CHANGELOG.md
components/firstpair/api/src/main/java/com/flipperdevices/firstpair/api/FirstPairFeatureEntry.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/api/FirstPairFeatureEntryImpl.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/viewmodel/ConnectViewModel.kt
components/singleactivity/impl/src/main/java/com/flipperdevices/singleactivity/impl/DeepLinkHelper.kt

**Background**
Now we can open first pair navigation from root graph
**Changes**
Open first pair screen by route graph
**Test plan**
Open first pair from info screen

Firstpair flow open by navigation graph route

---

CHANGELOG.md
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/executor/DiffKeyExecutor.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/repository/KeyDiffApplier.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/utils/ProgressWrapperTracker.kt

**Background**
Right now we not respect download to android phone, only upload to flipper in percents
**Changes**
- Respect download tasks also in percents
**Test plan**
Try synchronize with empty phone and full flipper

More smoothly synchronization percent

---

CHANGELOG.md
components/bottombar/impl/src/main/java/com/flipperdevices/bottombar/impl/composable/ComposableMainScreen.kt

**Background**
Right now we not reset tab on double tap
**Changes**
- Reset tab if it select right now
**Test plan**
Try press on tab if you already have stack on this tab

Reset tab on double tap

---

CHANGELOG.md
components/archive/impl/src/main/java/com/flipperdevices/archive/impl/api/ArchiveFeatureEntryImpl.kt

**Background**
Now we open key screen in bottom navigation
**Changes**
Use global navigation stack
**Test plan**
Try open key screen and go back

Open key screen in global scope

---

.github/workflows/pr.yml
.github/workflows/pr_gradle.yml
CHANGELOG.md

**Background**
Right now we don't run CI jobs in GitHub queue
**Changes**
- Add queue in github ci jobs
**Test plan**
Try merge with queue

Enable pipeline for queue

---

CHANGELOG.md
components/info/impl/src/main/java/com/flipperdevices/info/impl/compose/screens/ComposableFullDeviceInfoScreen.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/compose/screens/fullinfo/ComposableFullInfoDevice.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/viewmodel/deviceinfo/FullInfoViewModel.kt

**Background**
Right now we can't force update device info 
**Changes**
Invalidate full device info on refresh
**Test plan**
Try pull to refresh on full device info screen

Add pull to refresh to full device info

---

CHANGELOG.md
components/settings/impl/src/main/java/com/flipperdevices/settings/impl/composable/category/DebugCategory.kt
components/settings/impl/src/main/java/com/flipperdevices/settings/impl/composable/category/ExperimentalCategory.kt
components/settings/impl/src/main/java/com/flipperdevices/settings/impl/viewmodels/DebugViewModel.kt
components/settings/impl/src/main/java/com/flipperdevices/settings/impl/viewmodels/ExperimentalViewModel.kt

**Background**
Right now people ask about apps toggle in experimental settings
**Changes**
Move toggle in debug options
**Test plan**
Check that settings in experimental options not appears

Move apps from experimental settings to debug

---

CHANGELOG.md
components/nfc/mfkey32/screen/src/main/java/com/flipperdevices/nfc/mfkey32/screen/composable/ComposableMfKey32Screen.kt
components/nfc/mfkey32/screen/src/main/java/com/flipperdevices/nfc/mfkey32/screen/viewmodel/MfKey32ViewModel.kt
components/nfc/tools/api/src/main/java/com/flipperdevices/nfc/tools/api/NfcToolsApi.kt
components/nfc/tools/impl/src/main/java/com/flipperdevices/nfc/tools/impl/api/NfcToolsApiImpl.kt

**Background**
Right now we don't open dialog on press back on mfkey32
**Changes**
- Show dialog on back in mfkey32
- Fix crash with ulong parser
**Test plan**
Try press back on mfkey32

Fix mfkey32 crash and back press

---

CHANGELOG.md
components/bottombar/impl/src/main/java/com/flipperdevices/bottombar/impl/composable/ComposableInAppNotification.kt
components/bottombar/impl/src/main/java/com/flipperdevices/bottombar/impl/viewmodel/InAppNotificationViewModel.kt
components/core/ktx/src/main/java/com/flipperdevices/core/ktx/android/ComposeLifecycleKtx.kt
components/inappnotification/impl/src/main/java/com/flipperdevices/inappnotification/impl/storage/InAppNotificationStorageImpl.kt

**Background**
Right now we use compose dispatcher
**Changes**
Use lifecycle events for in app notification subscribe/unsubscribe
**Test plan**
Try show inapp notification and see in logs

Use lifecycle event for inapp notification

---

.github/workflows/release.yml
CHANGELOG.md
build-logic/plugins/convention/src/main/kotlin/com/flipperdevices/buildlogic/ApkConfig.kt
build-logic/plugins/convention/src/main/kotlin/commonAndroid.kt
components/selfupdater/source/googleplay/src/main/kotlin/com/flipperdevices/selfupdater/googleplay/api/SelfUpdaterGooglePlayApi.kt
instances/app/build.gradle.kts

**Background**
Right now we use internal for release build
**Changes**
- Use release build
- In RC build release build, but not publish it
**Test plan**
Try build release build

Use release build for release

---

CHANGELOG.md
components/analytics/shake2report/impl/src/main/java/com/flipperdevices/analytics/shake2report/impl/composable/states/ComposableReportPending.kt

**Background**
Right now we have problem with report bug on small screens
**Changes**
Add scroll to report bug screen
**Test plan**
Try open keyboard on report bug screen

Add scroll to report bug screen

---

CHANGELOG.md
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/FlipperBleManagerImpl.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/PeripheralResponseReader.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/service/request/FlipperRequestApiImpl.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/service/request/FlipperSerialApiUnsafeImpl.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/utils/BridgeImplConfig.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/executor/AndroidKeyStorage.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/model/KeyWithHash.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/repository/FavoriteSynchronization.kt
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/utils/KeyDiffCombiner.kt
components/bridge/synchronization/impl/src/test/java/com/flipperdevices/bridge/synchronization/impl/repository/favorites/FavoriteSynchronizationTest.kt
components/bridge/synchronization/impl/src/test/java/com/flipperdevices/bridge/synchronization/impl/repository/favorites/FavoriteSynchronizationTestParam.kt
components/bridge/synchronization/impl/src/test/java/com/flipperdevices/bridge/synchronization/impl/utils/KeyDiffCombinerTest.kt

**Background**
Right now if we have two similar diff action we just try add it one more time
**Changes**
- Write test on keydiffcombiner
- Delete both diffaction if it similar
**Test plan**
Try delete manifest file

Fix incorrect diff combiner, add KeyDiffCombinerTest

---

CHANGELOG.md
components/inappnotification/impl/src/main/java/com/flipperdevices/inappnotification/impl/composable/type/ComposableInAppNotificationUpdateReady.kt
components/inappnotification/impl/src/main/res/values/strings.xml

**Background**
* Bad scale text in notification
**Changes**
* Use weight for replace text in new line while font more
**Test plan**
See notification update for update

InAppNotification update redesign for font scale

---

CHANGELOG.md
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/utils/BridgeImplConfig.kt

**Background**
Right now ble have more flood in console
**Changes**
Disable ble log by default
**Test plan**
Try open application and see on logs

Disable verbose ble logging by default

---

CHANGELOG.md
components/bridge/rpcinfo/impl/src/main/java/com/flipperdevices/bridge/rpcinfo/impl/fullinforpc/NewFlipperFullInfoRpcApi.kt
components/bridge/rpcinfo/impl/src/main/java/com/flipperdevices/bridge/rpcinfo/impl/mapper/NewFlipperRpcInfoMapper.kt

**Background**
Right now sometimes different params can have similar key
**Changes**
Add source prefix for each key in new API
**Test plan**
Try open full info screen

Fix device info mapping keys

---

.idea/codeStyles/Project.xml
CHANGELOG.md
components/bridge/rpcinfo/api/src/main/java/com/flipperdevices/bridge/rpcinfo/api/FlipperStorageInformationApi.kt
components/bridge/rpcinfo/impl/src/main/java/com/flipperdevices/bridge/rpcinfo/impl/FlipperStorageInformationApiImpl.kt
components/bridge/rpcinfo/impl/src/test/java/com/flipperdevices/bridge/rpcinfo/impl/FlipperStorageInformationTest.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/viewmodel/deviceinfo/BasicInfoViewModel.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/helpers/StorageExistHelper.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/viewmodel/UpdateCardViewModel.kt
components/updater/subghz/src/test/kotlin/com/flipperdevices/updater/subghz/tasks/RegionProvisioningHelperTest.kt
gradle/libs.versions.toml

**Background**
Right now we show progress state on device info screen
**Changes**
Invalidate only if flipper active
**Test plan**
Try disconnect flipper and check device screen

Progress bar on disconnected state on device info screen

---

.idea/codeStyles/Project.xml
CHANGELOG.md
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/composable/searching/ComposableSearching.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/composable/searching/ComposableSearchingDevices.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/composable/searching/ComposableSearchingView.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/model/DevicePairState.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/model/SearchingState.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/viewmodels/SearchStateBuilder.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/viewmodels/connecting/FirstPairBleManager.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/viewmodels/connecting/PairDeviceViewModel.kt
components/firstpair/impl/src/main/res/values/strings.xml

**Background**
Right now we just stop pairing if connection failed
**Changes**
Suggest retry connection
**Test plan**
Try connect to flipper and drop/cancel connection

Add retry dialog on first pair

---

CHANGELOG.md
components/core/ui/dialog/src/main/java/com/flipperdevices/core/ui/dialog/composable/multichoice/FlipperMultiChoiceDialogModel.kt
components/core/ui/ktx/src/main/java/com/flipperdevices/core/ui/ktx/image/AsyncImageWithPlaceholder.kt
components/core/ui/theme/src/main/kotlin/com/flipperdevices/core/ui/theme/composable/AnimatedFlipperPalletProvider.kt
components/core/ui/theme/src/main/kotlin/com/flipperdevices/core/ui/theme/composable/FlipperPallet.kt
components/core/ui/theme/src/main/kotlin/com/flipperdevices/core/ui/theme/composable/FlipperPalletProvider.kt
components/faphub/appcard/composable/src/main/java/com/flipperdevices/faphub/appcard/composable/SmallHorizontalAppCard.kt
components/faphub/dao/network/src/main/java/com/flipperdevices/faphub/dao/network/api/FapNetworkApiImpl.kt
components/faphub/fapscreen/impl/build.gradle.kts
components/faphub/fapscreen/impl/src/main/java/com/flipperdevices/faphub/fapscreen/impl/composable/ComposableFapScreen.kt
components/faphub/fapscreen/impl/src/main/java/com/flipperdevices/faphub/fapscreen/impl/composable/header/ComposableDeleteConfirmDialog.kt
components/faphub/fapscreen/impl/src/main/res/values/strings.xml
components/faphub/installation/button/impl/src/main/java/com/flipperdevices/faphub/installation/button/impl/composable/elements/ComposableInProgressFapButton.kt
components/faphub/maincard/impl/src/main/java/com/flipperdevices/faphub/maincard/impl/composable/suggestion/ComposableSuggestion.kt
components/faphub/search/impl/src/main/res/values/strings.xml
components/faphub/utils/src/main/java/com/flipperdevices/faphub/utils/FapHubConstants.kt

**Background**
Right now we delete application without dialog
**Changes**
- Add confirm delete dialog
**Test plan**
Try delete app

Faphub delete confirm dialog

---

CHANGELOG.md
README.md

Add Fdroid badge
**Background**
Flipper App is in fdroid
**Changes**
Update with link to fdroid version
**Test plan**
Look at new README.md

Update README.md with fdroid

---

CHANGELOG.md
components/keyscreen/api/src/main/java/com/flipperdevices/keyscreen/api/KeyScreenApi.kt
components/keyscreen/api/src/main/java/com/flipperdevices/keyscreen/api/KeyStateHelperApi.kt
components/keyscreen/api/src/main/java/com/flipperdevices/keyscreen/model/DeleteState.kt
components/keyscreen/api/src/main/java/com/flipperdevices/keyscreen/model/FavoriteState.kt
components/keyscreen/api/src/main/java/com/flipperdevices/keyscreen/model/KeyScreenState.kt
components/keyscreen/api/src/main/java/com/flipperdevices/keyscreen/model/ShareState.kt
components/keyscreen/impl/build.gradle.kts
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/api/KeyScreenApiImpl.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/api/KeyStateHelperImpl.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/ComposableKeyParsed.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/ComposableKeyScreen.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/actions/ComposableDelete.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/actions/ComposableFavorite.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/actions/ComposableShare.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/card/ComposableCardTitle.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/card/ComposableKeyCard.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/model/FlipperDeviceState.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/viewmodel/KeyScreenViewModel.kt
components/keyscreen/impl/src/test/kotlin/com/flipperdevices/keyscreen/impl/viewmodel/KeyScreenViewModelTest.kt

**Background**
Refactor keyscreen for integrate infrarred
**Changes**
* Model and API move to keyscreen:api module
* Use Builder for KeyStateHelper
* Test for KeyScreenVM
**Test plan**
Green pipeline

Share key state and card by api module

---

CHANGELOG.md
components/bottombar/api/src/main/java/com/flipperdevices/bottombar/api/BottomNavigationHandleDeeplink.kt
components/bottombar/api/src/main/java/com/flipperdevices/bottombar/model/BottomBarTab.kt
components/bottombar/impl/src/main/java/com/flipperdevices/bottombar/impl/api/BottomNavigationFeatureEntryImpl.kt
components/bottombar/impl/src/main/java/com/flipperdevices/bottombar/impl/composable/ComposableMainScreen.kt
components/faphub/installation/button/impl/build.gradle.kts
components/faphub/installation/button/impl/src/main/java/com/flipperdevices/faphub/installation/button/impl/api/FapInstallationUIApiImpl.kt
components/faphub/installation/button/impl/src/main/java/com/flipperdevices/faphub/installation/button/impl/composable/ComposableFapButtons.kt
components/faphub/installation/button/impl/src/main/java/com/flipperdevices/faphub/installation/button/impl/composable/dialogs/ComposableFlipperNotConnectedDialog.kt
components/faphub/installation/button/impl/src/main/res/values/strings.xml
components/faphub/installation/stateprovider/impl/src/main/java/com/flipperdevices/faphub/installation/stateprovider/impl/api/FapInstallationStateManagerImpl.kt

**Background**
Right now we don't show any information when flipper not connected
**Changes**
Show request flipper connect dialog
**Test plan**
Try disconnect flipper and click on install button

Add flipper not connected dialog

---

CHANGELOG.md
components/archive/shared/src/test/kotlin/com/flipperdevices/archive/shared/ExtractKeyMetaInformationTest.kt
components/keyparser/api/src/main/kotlin/com/flipperdevices/keyparser/api/model/FlipperKeyParsed.kt
components/keyparser/impl/src/main/kotlin/com/flipperdevices/keyparser/impl/parsers/impl/InfraredParser.kt
components/keyparser/impl/src/test/assets/example.ir
components/keyparser/impl/src/test/kotlin/com/flipperdevices/keyparser/impl/InfraredParserTest.kt

**Background**
Now, we not parse remotes name in infared key
**Changes**
Parse remotes name + test
**Test plan**
Now, nothing

 Infrared Emulate (parse name remotes)

---

CHANGELOG.md
components/core/preference/src/main/proto/settings.proto
components/faphub/dao/network/src/main/java/com/flipperdevices/faphub/dao/network/retrofit/KtorfitModule.kt
components/settings/impl/src/main/java/com/flipperdevices/settings/impl/composable/category/DebugCategory.kt
components/settings/impl/src/main/java/com/flipperdevices/settings/impl/viewmodels/DebugViewModel.kt
components/settings/impl/src/main/res/values/strings.xml

**Background**
Right now we can't use release catalog
**Changes**
- Add debug url and switch in debug settings

Add release catalog url

---

CHANGELOG.md
components/share/receive/src/main/java/com/flipperdevices/share/receive/composable/ComposableKeyReceive.kt

**Background**
Now, when we go open key link and press save key, we have a white screen
**Changes**
Single call finish and cancel button on finish state
**Test plan**
Try open key link

Fix white screen after import key

---

CHANGELOG.md
components/faphub/dao/network/src/main/java/com/flipperdevices/faphub/dao/network/api/FapDownloadApiImpl.kt
components/faphub/dao/network/src/main/java/com/flipperdevices/faphub/dao/network/retrofit/api/KtorfitBundleApi.kt
components/faphub/installation/queue/impl/src/main/java/com/flipperdevices/faphub/installation/queue/impl/executor/InstallationActionExecutor.kt
components/faphub/installation/queue/impl/src/main/java/com/flipperdevices/faphub/installation/queue/impl/executor/PrepareFapActionExecutor.kt
components/faphub/installation/queue/impl/src/main/java/com/flipperdevices/faphub/installation/queue/impl/executor/UpdateActionExecutor.kt

**Background**
Right now we can't download build for FapHub
**Changes**
- Fix endpoint
**Test plan**
Try install application

Fix endpoint for fap hub build download

---

CHANGELOG.md
components/faphub/fapscreen/impl/src/main/java/com/flipperdevices/faphub/fapscreen/impl/composable/header/ComposableFapBuildStatus.kt

**Background**
Right now we have incorrect layout
**Changes**
Hide left empty icon if hide attention icon
| ![telegram-cloud-photo-size-2-5289836006025055865-y](https://github.com/flipperdevices/Flipper-Android-App/assets/5871715/ea313369-e667-40e3-b8e2-9bba28decd7b) | ![telegram-cloud-photo-size-2-5289836006025055866-y](https://github.com/flipperdevices/Flipper-Android-App/assets/5871715/9db1f44b-38a3-4d55-817d-a755f911cfa3) |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Old layout …

Fix FapHub build status layout

---

CHANGELOG.md
components/faphub/category/impl/src/main/java/com/flipperdevices/faphub/category/impl/composable/ComposableFapHubCategoryScreen.kt
components/faphub/fapscreen/impl/src/main/java/com/flipperdevices/faphub/fapscreen/impl/composable/ComposableFapScreen.kt
components/faphub/fapscreen/impl/src/main/java/com/flipperdevices/faphub/fapscreen/impl/viewmodel/FapScreenViewModel.kt

**Background**
Right now we have pull to refresh to faphub 
**Changes**
- Pull to refresh to App Screen
- Pull to refresh to Category Screen
**Test plan**
Try pull to refresh

Add pull to refresh to faphub app screen and categories

---

components/settings/impl/src/main/java/com/flipperdevices/settings/impl/composable/category/DebugCategory.kt
components/settings/impl/src/main/java/com/flipperdevices/settings/impl/composable/category/ExperimentalCategory.kt
components/settings/impl/src/main/java/com/flipperdevices/settings/impl/viewmodels/DebugViewModel.kt
components/settings/impl/src/main/java/com/flipperdevices/settings/impl/viewmodels/ExperimentalViewModel.kt

**Background**
Now Infrared in experimental options
**Changes**
* Flag in DebugVM
**Test plan**
Go to options and see infrared point in debug options

Infrared in debug options

---

CHANGELOG.md
components/analytics/shake2report/noop/src/main/java/com/flipperdevices/shake2report/noop/Shake2ReportStub.kt
components/settings/impl/src/main/java/com/flipperdevices/settings/impl/composable/category/OtherSettingsCategory.kt
gradle/libs.versions.toml
instances/app/proguard-rules.pro

**Background**
Right now we crash with ktorfit
**Changes**
- Add proguard rules for ignore some ktor files
**Test plan**
Try run fdroid build

Fix fdroid build

---

CHANGELOG.md
gradle/libs.versions.toml

**Background**
https://github.com/oleksandrbalan/modalsheet/issues/32
**Changes**
Upgrade to beta version, because for downgrade, we need to downgrade compose too
**Test plan**
Try open key screen

Upgrade google appcompanist

---

CHANGELOG.md
components/bridge/rpc/impl/src/main/java/com/flipperdevices/bridge/rpc/impl/delegates/FlipperListingDelegate.kt

**Background**
Now, if we don't have folder for apps, catalog not display button install 
**Changes**
Check code ERROR_STORAGE_NOT_EXIST and return empty list
**Test plan**
Format SD card and try to install some apps

If flipper path not exist - return empty list,

---

.github/workflows/internal.yml
.github/workflows/release.yml
CHANGELOG.md
components/bottombar/impl/src/main/java/com/flipperdevices/bottombar/impl/composable/ComposableMainScreen.kt
components/bridge/api/src/main/java/com/flipperdevices/bridge/api/utils/Constants.kt
components/bridge/rpc/impl/src/main/java/com/flipperdevices/bridge/rpc/impl/delegates/FlipperListingDelegate.kt
components/core/ui/navigation/build.gradle.kts
components/core/ui/tabswitch/src/main/java/com/flipperdevices/core/ui/tabswitch/ComposableTabswitch.kt
components/faphub/dao/network/src/main/java/com/flipperdevices/faphub/dao/network/ktorfit/api/KtorfitCategoryApi.kt
components/faphub/dao/network/src/main/java/com/flipperdevices/faphub/dao/network/ktorfit/utils/FapHubNetworkCategoryApi.kt
components/keyscreen/impl/build.gradle.kts
components/nfceditor/impl/build.gradle.kts
components/share/uploader/build.gradle.kts
components/singleactivity/impl/src/main/java/com/flipperdevices/singleactivity/impl/composable/ComposableSingleActivityNavHost.kt
gradle/libs.versions.toml

**Background**
Preparation for release
**Changes**
- Fix version conflict on CI with Google Play deploy
- Add support for size filter in listing request
- Fix corner padding radius in switch tab
- Fix faphub category GET request
- Downgrade compose navigation for fix transit animation
- Remove compose insets
**Test plan**
Test RC

Fix CI and some preparation for release

---

CHANGELOG.md
components/keyscreen/api/build.gradle.kts
components/keyscreen/api/src/main/java/com/flipperdevices/keyscreen/model/KeyScreenState.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/api/KeyStateHelperImpl.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/ComposableKeyScreen.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/viewmodel/KeyScreenViewModel.kt
components/keyscreen/impl/src/test/kotlin/com/flipperdevices/keyscreen/impl/viewmodel/KeyScreenViewModelTest.kt

**Background**
Right now we can't emulate button on key screen
**Changes**
Use ready state for deliver emulate config
**Test plan**
Try emulate keys

Fix key emulate button

---

CHANGELOG.md
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/api/FirstPairFeatureEntryImpl.kt
components/wearable/core/ui/components/build.gradle.kts
components/wearable/core/ui/components/src/main/java/com/flipperdevices/wearable/core/ui/components/ComposableWearOsScrollableColumn.kt
components/wearable/emulate/wear/impl/build.gradle.kts
components/wearable/emulate/wear/impl/src/main/java/com/flipperdevices/wearable/emulate/impl/api/WearEmulateApiImpl.kt
components/wearable/setup/impl/src/main/java/com/flipperdevices/wearable/setup/impl/composable/ComposableFindPhone.kt
components/wearable/sync/wear/impl/build.gradle.kts
components/wearable/sync/wear/impl/src/main/java/com/flipperdevices/wearable/sync/wear/impl/composable/ComposableKeysList.kt

**Background**
Right now we have some screen which not scrollable on WearOS
**Changes**
Use scroll for all screens with text
**Test plan**
Use large font and open all screens

Fix wearos font issue

---

.github/workflows/internal.yml
CHANGELOG.md
components/analytics/metric/api/src/main/java/com/flipperdevices/metric/api/MetricApi.kt
components/analytics/metric/api/src/main/java/com/flipperdevices/metric/api/events/SimpleEvent.kt
components/analytics/metric/impl/src/main/java/com/flipperdevices/metric/impl/api/MetricApiImpl.kt
components/analytics/metric/impl/src/main/java/com/flipperdevices/metric/impl/clickhouse/ClickhouseApi.kt
components/analytics/metric/impl/src/main/java/com/flipperdevices/metric/impl/clickhouse/ClickhouseApiImpl.kt
components/analytics/metric/noop/src/main/java/com/flipperdevices/metric/noop/NoopMetricApiImpl.kt
components/faphub/category/impl/build.gradle.kts
components/faphub/category/impl/src/main/java/com/flipperdevices/faphub/category/impl/api/FapHubCategoryApiImpl.kt
components/faphub/fapscreen/impl/build.gradle.kts
components/faphub/fapscreen/impl/src/main/java/com/flipperdevices/faphub/fapscreen/impl/viewmodel/FapScreenViewModel.kt
components/faphub/installation/queue/impl/build.gradle.kts
components/faphub/installation/queue/impl/src/main/java/com/flipperdevices/faphub/installation/queue/impl/api/FapQueueRunner.kt
components/faphub/main/impl/build.gradle.kts
components/faphub/main/impl/src/main/java/com/flipperdevices/main/impl/api/FapHubMainScreenApiImpl.kt
components/faphub/search/impl/build.gradle.kts
components/faphub/search/impl/src/main/java/com/flipperdevices/faphub/search/impl/api/FapHubSearchEntryApiImpl.kt
components/hub/impl/build.gradle.kts
components/hub/impl/src/main/java/com/flipperdevices/hub/impl/api/HubFeatureEntryImpl.kt

**Background**
Right now we can't understand how many users use faphub catalog
**Changes**
Add faphub metrics
**Test plan**
Test each metric event

Add faphub metric

---

CHANGELOG.md
components/faphub/appcard/composable/src/main/java/com/flipperdevices/faphub/appcard/composable/AppCard.kt
components/faphub/appcard/composable/src/main/java/com/flipperdevices/faphub/appcard/composable/SmallHorizontalAppCard.kt
components/faphub/appcard/composable/src/main/java/com/flipperdevices/faphub/appcard/composable/components/ComposableAppCategory.kt
components/faphub/appcard/composable/src/main/java/com/flipperdevices/faphub/appcard/composable/components/ComposableAppIcon.kt
components/faphub/appcard/composable/src/main/java/com/flipperdevices/faphub/appcard/composable/paging/ComposableFapsList.kt
components/faphub/appcard/composable/src/main/java/com/flipperdevices/faphub/appcard/composable/paging/ComposableSortChoice.kt
components/faphub/installation/button/impl/src/main/java/com/flipperdevices/faphub/installation/button/impl/composable/buttons/ComposableFapOpeningButton.kt
components/faphub/installation/button/impl/src/main/java/com/flipperdevices/faphub/installation/button/impl/composable/elements/ComposableFlipperButton.kt
components/faphub/installation/button/impl/src/main/java/com/flipperdevices/faphub/installation/button/impl/composable/elements/ComposableInProgressFapButton.kt
components/faphub/installation/button/impl/src/main/res/values/strings.xml
components/faphub/main/impl/src/main/java/com/flipperdevices/main/impl/composable/switch/ComposableFapHubSwitch.kt
components/faphub/target/impl/src/main/java/com/flipperdevices/faphub/target/impl/api/FlipperTargetProviderApiImpl.kt

**Background**
Right now we have old design
**Changes**
New paddings, buttons and colors
| ![photo_2023-09-19_18-02-07](https://github.com/flipperdevices/Flipper-Android-App/assets/5871715/40d73770-ab9e-4dde-b920-7555240fe0a5) | ![photo_2023-09-19_18-02-06](https://github.com/flipperdevices/Flipper-Android-App/assets/5871715/ee1c757c-28ce-4488-b21b-bc214ba6962f) | ![photo_2023-09-19_18-02-05](https://github.com/flipperdevices/Flipper-Android-App/assets/5871715/40ad2370-aec3-49d9-a6b0-4df1b097f100) |
|:---------------------------------------------------------------------------------------------------------------------------------------:|:---------------------------------------------------------------------------------------------------------------------------------------:|------------------ …

Redesign for FapHub

---

CHANGELOG.md
components/faphub/fapscreen/impl/src/main/res/values/strings.xml
components/faphub/installation/button/impl/src/main/res/values/strings.xml

**Background**
Now "Go To Device Screen" not explain about problem
**Changes**
Changes texts
**Test plan**
See text on button

Update Go To Device Screen text in catalog

---

CHANGELOG.md
components/updater/screen/src/main/res/values/strings.xml

**Background**
Now uses another apostrophe
**Changes**
"What’s New"
**Test plan**
Try to update on OFW and see text

Fix apostrophe in text "What’s New"

---

CHANGELOG.md
components/settings/impl/src/main/java/com/flipperdevices/settings/impl/composable/category/ExperimentalCategory.kt
components/settings/impl/src/main/java/com/flipperdevices/settings/impl/viewmodels/ExperimentalViewModel.kt

**Background**
No we have Remote Control in Hub
**Changes**
Remove UI and function from VM
**Test plan**
Go to Options -> Experimental

Remove Control from Options

---

CHANGELOG.md
components/faphub/fapscreen/impl/src/main/java/com/flipperdevices/faphub/fapscreen/impl/composable/description/ComposableDeveloperFooter.kt
components/faphub/fapscreen/impl/src/main/java/com/flipperdevices/faphub/fapscreen/impl/composable/description/ComposableFapHide.kt
components/faphub/fapscreen/impl/src/main/java/com/flipperdevices/faphub/fapscreen/impl/composable/description/ComposableFapReport.kt

**Background**
Bold W400
**Changes**
Replace Bold W400 to Bold W%00
**Test plan**
Go to FAP screen and Github link and app action

Bold Text in Github link and app action

---

CHANGELOG.md
components/analytics/metric/api/src/main/java/com/flipperdevices/metric/api/MetricApi.kt
components/analytics/metric/api/src/main/java/com/flipperdevices/metric/api/events/SessionState.kt
components/analytics/metric/impl/src/main/java/com/flipperdevices/metric/impl/api/MetricApiImpl.kt
components/analytics/metric/impl/src/main/java/com/flipperdevices/metric/impl/countly/CountlyApi.kt
components/analytics/metric/impl/src/main/java/com/flipperdevices/metric/impl/countly/CountlyApiImpl.kt
components/analytics/metric/noop/src/main/java/com/flipperdevices/metric/noop/NoopMetricApiImpl.kt
components/singleactivity/impl/src/main/java/com/flipperdevices/singleactivity/impl/SingleActivity.kt

**Background**
Add countly session
**Changes**
- Handle session by countly
**Test plan**
See countly dashboard

Add countly sessions

---

CHANGELOG.md
components/core/ui/ktx/src/main/java/com/flipperdevices/core/ui/ktx/elements/SwipeRefresh.kt
components/faphub/appcard/composable/src/main/java/com/flipperdevices/faphub/appcard/composable/AppCard.kt
components/faphub/catalogtab/impl/src/main/java/com/flipperdevices/faphub/catalogtab/impl/composable/ComposableCatalogTab.kt
components/faphub/installation/button/impl/src/main/java/com/flipperdevices/faphub/installation/button/impl/helper/OpenFapHelper.kt
components/faphub/installedtab/impl/src/main/java/com/flipperdevices/faphub/installedtab/impl/composable/ComposableInstalledTabScreen.kt
components/faphub/main/impl/src/main/java/com/flipperdevices/main/impl/composable/switch/ComposableFapHubSwitch.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/composable/searching/ComposableSearchingDevices.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/compose/screens/ComposableDeviceInfoScreen.kt
components/widget/screen/src/main/java/com/flipperdevices/widget/screen/compose/ComposableKeys.kt

**Background**
Right now we have some small bugs in app
**Changes**
- Fix installed tab "need to update" count
- Fix fap app icon size in large app card
- Fix openning animation
- Fix swipe refresh modifier use in root level
**Test plan**
Small layout and logic fixes

Fix installed tab "need to update" count

---

CHANGELOG.md
components/updater/card/src/main/java/com/flipperdevices/updater/card/helpers/UpdateOfferProvider.kt
components/updater/card/src/test/kotlin/com/flipperdevices/updater/card/helpers/UpdateOfferProviderTest.kt
components/updater/impl/src/main/java/com/flipperdevices/updater/impl/api/UpdaterApiImpl.kt

**Background**
Right now we have problem with infinite update button active
**Changes**
- Reinvalidate update button when connection state changed
**Test plan**
Try update flipper

Try fix "The firmware update button is constantly active until the application is restarted"

---

CHANGELOG.md
components/faphub/dao/network/src/main/java/com/flipperdevices/faphub/dao/network/api/FapNetworkApiImpl.kt
components/faphub/dao/network/src/main/java/com/flipperdevices/faphub/dao/network/api/FapVersionApiImpl.kt
components/faphub/dao/network/src/main/java/com/flipperdevices/faphub/dao/network/helper/FapApplicationReceiveHelper.kt
components/faphub/dao/network/src/main/java/com/flipperdevices/faphub/dao/network/ktorfit/KtorfitModule.kt
components/faphub/dao/network/src/main/java/com/flipperdevices/faphub/dao/network/ktorfit/api/KtorfitApplicationApi.kt
components/faphub/dao/network/src/main/java/com/flipperdevices/faphub/dao/network/ktorfit/api/KtorfitBundleApi.kt
components/faphub/dao/network/src/main/java/com/flipperdevices/faphub/dao/network/ktorfit/api/KtorfitCategoryApi.kt
components/faphub/dao/network/src/main/java/com/flipperdevices/faphub/dao/network/ktorfit/api/KtorfitVersionApi.kt
components/faphub/dao/network/src/main/java/com/flipperdevices/faphub/dao/network/ktorfit/model/requests/KtorfitApplicationApiRequest.kt
components/faphub/dao/network/src/main/java/com/flipperdevices/faphub/dao/network/ktorfit/model/requests/KtorfitDetailedVersionRequest.kt

**Background**
Right now we use deprecated http request scheme
**Changes**
Use new http request scheme
**Test plan**
Just open faphub catalog

Migrate to new connection REST scheme to FapHub

---

CHANGELOG.md
components/share/receive/build.gradle.kts
components/share/receive/src/main/java/com/flipperdevices/share/receive/viewmodels/KeyReceiveViewModel.kt

**Background**
Now we not correct handle exception after open expired link
**Changes**
* Use ktor exception ClientRequestException with check code
**Test plan**
* Try open https://flpr.app/sf#path=infrared/Selo_tv.ir&id=nLoer3&key=S0BWADnRlnhxQEU9jMwFsQ

Handle expired flipper crypto link

---

CHANGELOG.md
components/archive/category/src/main/res/values/strings.xml
components/faphub/fapscreen/impl/src/main/java/com/flipperdevices/faphub/fapscreen/impl/composable/header/ComposableFapBuildStatusDialog.kt
components/faphub/fapscreen/impl/src/main/res/values/strings.xml
components/faphub/installation/button/impl/src/main/res/values/strings.xml
components/faphub/installedtab/impl/src/main/res/values/strings.xml
components/faphub/maincard/impl/src/main/res/values/strings.xml
components/firstpair/impl/src/main/res/values/strings.xml
components/inappnotification/impl/src/main/res/values/strings.xml
components/info/shared/src/main/res/values/strings.xml
components/keyscreen/impl/src/main/res/values/strings.xml
components/nfc/mfkey32/screen/src/main/res/values/strings.xml
components/nfc/tools/impl/build.gradle.kts
components/updater/card/src/main/res/values/strings.xml
components/updater/screen/src/main/res/values/strings.xml

**Background**
Right now we have some problems with text
**Changes**
- Fix small typos in texts and fix layout
**Test plan**
Check texts

App text refactor

---

CHANGELOG.md
components/analytics/metric/api/src/main/java/com/flipperdevices/metric/api/events/complex/DebugInfoEvent.kt
components/analytics/metric/impl/src/main/java/com/flipperdevices/metric/impl/clickhouse/ClickhouseApiImpl.kt
components/keyscreen/api/src/main/java/com/flipperdevices/keyscreen/model/KeyScreenState.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/api/KeyScreenViewDecomposeComponentImpl.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/api/KeyStateHelperImpl.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/ComposableKeyParsed.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/ComposableKeyScreen.kt
components/keyscreen/impl/src/test/kotlin/com/flipperdevices/keyscreen/impl/viewmodel/KeyScreenViewModelTest.kt
components/nfceditor/api/src/main/java/com/flipperdevices/nfceditor/api/NfcEditorApi.kt
components/nfceditor/impl/src/main/java/com/flipperdevices/nfceditor/impl/api/NfcEditorApiImpl.kt

**Background**
Right now we don't support new format of NFC Mifare Classic 
**Changes**
- Add unupported metric for nfc format
- Add support for 4 nfc format
**Test plan**
Try open screen on 4 version of nfc format

Add new nfc format and metric on unsupported format

---

CHANGELOG.md
components/archive/impl/src/main/java/com/flipperdevices/archive/impl/viewmodel/CategoryViewModel.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/manager/service/request/FlipperSerialApiUnsafeImpl.kt
components/core/ktx/src/main/java/com/flipperdevices/core/ktx/jre/IterratorKtx.kt
components/core/ui/theme/src/main/kotlin/com/flipperdevices/core/ui/theme/viewmodel/ThemeViewModel.kt
components/faphub/catalogtab/impl/src/main/java/com/flipperdevices/faphub/catalogtab/impl/composable/ComposableCatalogTab.kt
components/faphub/catalogtab/impl/src/main/java/com/flipperdevices/faphub/catalogtab/impl/viewmodel/FapsListViewModel.kt
components/faphub/category/impl/src/main/java/com/flipperdevices/faphub/category/impl/api/FapHubCategoryScreenDecomposeComponentImpl.kt
components/faphub/category/impl/src/main/java/com/flipperdevices/faphub/category/impl/viewmodel/FapHubCategoryViewModel.kt
components/faphub/installedtab/impl/src/main/java/com/flipperdevices/faphub/installedtab/impl/model/FapBatchUpdateButtonState.kt
components/faphub/installedtab/impl/src/main/java/com/flipperdevices/faphub/installedtab/impl/model/FapInstalledScreenState.kt
components/faphub/installedtab/impl/src/main/java/com/flipperdevices/faphub/installedtab/impl/viewmodel/InstalledFapsViewModel.kt
components/nfc/attack/impl/src/main/java/com/flipperdevices/nfc/attack/impl/viewmodel/NfcAttackViewModel.kt
components/notification/api/src/main/java/com/flipperdevices/notification/api/FlipperAppNotificationApi.kt
components/notification/impl/src/main/java/com/flipperdevices/notification/api/FlipperAppNotificationApiImpl.kt
components/notification/impl/src/main/java/com/flipperdevices/notification/api/FlipperAppNotificationDialogApiImpl.kt
components/notification/impl/src/main/java/com/flipperdevices/notification/viewmodel/NotificationDialogViewModel.kt
components/settings/impl/src/main/java/com/flipperdevices/settings/impl/viewmodels/NotificationViewModel.kt
components/settings/impl/src/main/java/com/flipperdevices/settings/impl/viewmodels/SettingsViewModel.kt
components/updater/api/src/main/java/com/flipperdevices/updater/api/FlipperVersionProviderApi.kt
components/updater/impl/src/main/java/com/flipperdevices/updater/impl/api/FlipperVersionProviderApiImpl.kt

**Background**
Right now sometimes we use stateIn function in wrong way
**Changes**
Remove all `stateIn` usage
**Test plan**
Right now we always keep in memory state in viewmode

Fix blinking caused on wrong stateIn used function

---

CHANGELOG.md
components/bottombar/api/build.gradle.kts
components/bottombar/impl/src/main/java/com/flipperdevices/bottombar/impl/composable/ComposableMainScreen.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/api/KeyStateHelperImpl.kt

**Background**
Right now app crashed when invoke key deletion
**Changes**
- Execute `onEndAction` on main thread
**Test plan**
Try delete and restore keys

Fix crash on delete key

---

CHANGELOG.md
components/bridge/synchronization/impl/src/main/java/com/flipperdevices/bridge/synchronization/impl/repository/manifest/ManifestStorage.kt
components/bridge/synchronization/impl/src/test/java/com/flipperdevices/bridge/synchronization/impl/repository/favorites/FavoriteSynchronizationTestSingle.kt

**Background**
Right now we can have broken manifest file
**Changes**
- Replace manifest file on read error
- Write in atomic mode
**Test plan**
Try use failed manifest file

Atomic write/read manifest storage

---

CHANGELOG.md
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/model/DevicePairState.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/viewmodels/connecting/PairDeviceViewModel.kt

**Background**
Right now sometimes connect button not react on tap
**Changes**
- Enable in progress status immediately after press on button
**Test plan**
Try pair flipper and check animation on connect button

Try to fix impact for connect button

---

CHANGELOG.md
components/core/ui/theme/src/main/kotlin/com/flipperdevices/core/ui/theme/composable/AnimatedFlipperPalletProvider.kt
components/core/ui/theme/src/main/kotlin/com/flipperdevices/core/ui/theme/composable/FlipperPallet.kt
components/core/ui/theme/src/main/kotlin/com/flipperdevices/core/ui/theme/composable/FlipperPalletProvider.kt
components/infrared/impl/src/main/kotlin/com/flipperdevices/infrared/impl/composable/ComposableInfraredScreen.kt
components/infrared/impl/src/main/kotlin/com/flipperdevices/infrared/impl/composable/components/ComposableInfraredAppBar.kt
components/infrared/impl/src/main/kotlin/com/flipperdevices/infrared/impl/composable/components/ComposableInfraredOptions.kt
components/keyemulate/api/src/main/kotlin/com/flipperdevices/keyemulate/api/KeyEmulateUiApi.kt
components/keyemulate/impl/src/main/java/com/flipperdevices/keyemulate/api/KeyEmulateUiApiImpl.kt
components/keyemulate/impl/src/main/java/com/flipperdevices/keyemulate/composable/ComposableInfraredSendButton.kt
components/keyemulate/impl/src/main/java/com/flipperdevices/keyemulate/composable/ComposableSimpleEmulateButton.kt
components/keyemulate/impl/src/main/java/com/flipperdevices/keyemulate/composable/ComposableSubGhzSendButton.kt
components/keyemulate/impl/src/main/java/com/flipperdevices/keyemulate/composable/common/ComposableActionDisable.kt
components/keyemulate/impl/src/main/java/com/flipperdevices/keyemulate/composable/common/ComposableActionLoading.kt
components/keyemulate/impl/src/main/java/com/flipperdevices/keyemulate/composable/common/ComposableEmulateButtonWithText.kt
components/keyemulate/impl/src/main/java/com/flipperdevices/keyemulate/helpers/EmulateHelperImpl.kt
components/keyemulate/impl/src/main/java/com/flipperdevices/keyemulate/viewmodel/EmulateViewModel.kt
components/keyemulate/impl/src/main/java/com/flipperdevices/keyemulate/viewmodel/InfraredViewModel.kt
components/keyemulate/impl/src/main/java/com/flipperdevices/keyemulate/viewmodel/SubGhzViewModel.kt
components/keyscreen/api/src/main/java/com/flipperdevices/keyscreen/model/KeyScreenState.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/api/KeyScreenApiImpl.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/api/KeyStateHelperImpl.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/ComposableKeyParsed.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/actions/ComposableNfcEdit.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/actions/common/ComposableActionContent.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/card/ComposableCardTitle.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/composable/card/ComposableKeyCard.kt
components/keyscreen/impl/src/test/kotlin/com/flipperdevices/keyscreen/impl/viewmodel/KeyScreenViewModelTest.kt

**Background**
Right now we can edit key when emulating is active
**Changes**
Allow edit only when emulating not active
**Test plan**
Try emulate key and edit key

Disable edit when emulating in progress

---

CHANGELOG.md
components/bridge/api/src/main/java/com/flipperdevices/bridge/api/manager/observers/ConnectionObserverComposite.kt
components/bridge/impl/src/main/java/com/flipperdevices/bridge/impl/scanner/FlipperScannerImpl.kt
components/core/test/build.gradle.kts
components/core/test/src/main/java/com/flipperdevices/core/test/DecomposeViewModelCoroutineScopeProviderKtx.kt
components/core/ui/lifecycle/src/main/java/com/flipperdevices/core/ui/lifecycle/DecomposeViewModel.kt
components/core/ui/lifecycle/src/main/java/com/flipperdevices/core/ui/lifecycle/DecomposeViewModelCoroutineScopeProvider.kt
components/firstpair/impl/build.gradle.kts
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/composable/searching/ComposableSearchingDevices.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/model/DevicePairState.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/model/SearchingState.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/viewmodels/SearchStateBuilder.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/viewmodels/connecting/FirstPairBleManager.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/viewmodels/connecting/PairDeviceViewModel.kt
components/firstpair/impl/src/test/kotlin/com/flipperdevices/firstpair/impl/viewmodels/connecting/PairDeviceViewModelTest.kt

**Background**
Now sometimes the connection takes forever after clicking on the Connect button on the first pair screen
**Changes**
Subscribe on state update before start connecting process
**Test plan**
Run unit tests

Fix bug with infinite connect state in first pair

---

CHANGELOG.md
components/archive/impl/src/main/java/com/flipperdevices/archive/impl/api/ArchiveScreenDecomposeComponentImpl.kt
components/faphub/category/impl/src/main/java/com/flipperdevices/faphub/category/impl/api/FapHubCategoryScreenDecomposeComponentImpl.kt
components/faphub/fapscreen/impl/src/main/java/com/flipperdevices/faphub/fapscreen/impl/api/ScreenDecomposeComponentImpl.kt
components/faphub/main/impl/src/main/java/com/flipperdevices/main/impl/api/MainScreenDecomposeComponentImpl.kt
components/faphub/report/impl/src/main/kotlin/com/flipperdevices/faphub/report/impl/api/FapReportSelectDecomposeComponentImpl.kt
components/faphub/search/impl/src/main/java/com/flipperdevices/faphub/search/impl/api/SearchScreenDecomposeComponentImpl.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/api/FileManagerListingComponent.kt
components/firstpair/impl/src/main/java/com/flipperdevices/firstpair/impl/api/FirstPairDecomposeComponentImpl.kt
components/hub/impl/src/main/java/com/flipperdevices/hub/impl/api/HubMainScreenDecomposeComponentImpl.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/api/UpdateScreenDecomposeComponent.kt
components/infrared/impl/src/main/kotlin/com/flipperdevices/infrared/impl/api/InfraredViewDecomposeComponentImpl.kt
components/keyscreen/impl/src/main/java/com/flipperdevices/keyscreen/impl/api/KeyScreenViewDecomposeComponentImpl.kt
components/nfc/attack/impl/src/main/java/com/flipperdevices/nfc/attack/impl/api/NFCAttackScreenDecomposeComponentImpl.kt
components/nfceditor/impl/src/main/java/com/flipperdevices/nfceditor/impl/api/NfcEditorScreenDecomposeComponentImpl.kt
components/rootscreen/impl/src/main/kotlin/com/flipperdevices/rootscreen/impl/api/RootDecomposeComponentImpl.kt
components/rootscreen/impl/src/main/kotlin/com/flipperdevices/rootscreen/impl/deeplink/RootDeeplinkHandler.kt
components/settings/impl/src/main/java/com/flipperdevices/settings/impl/api/MainScreenDecomposeComponent.kt
components/settings/impl/src/main/java/com/flipperdevices/settings/impl/viewmodels/DebugViewModel.kt
components/settings/impl/src/main/java/com/flipperdevices/settings/impl/viewmodels/ExperimentalViewModel.kt
components/wearable/sync/wear/impl/src/main/java/com/flipperdevices/wearable/sync/wear/impl/api/KeysListDecomposeComponentImpl.kt
components/widget/screen/src/main/java/com/flipperdevices/widget/screen/api/WidgetOptionsDecomposeComponentImpl.kt

**Background**
Right now if config exist in stack decompose crush application
**Changes**
Use `pushToFront` instead of `push`
**Test plan**
Try open same config

Replace decompose push to move safety push

---

.github/workflows/internal.yml

**Background**
Please, describe here why you create this PR
**Changes**
Here what change in this PR..
**Test plan**

Internal wf arc runner set

---

.github/workflows/call-create-baseline.yml
.github/workflows/internal.yml
.github/workflows/release.yml

**Background**
Fix baseline workflow `:components:bridge:pbutils`
**Changes**
- Added recursive checkout
- Fix workflow names
**Test plan**
- Run GH actions

Fix baseline workflow

---

.github/workflows/call-create-baseline.yml
.github/workflows/internal.yml
.github/workflows/release.yml

**Background**
Github CI with workflow not correct
**Changes**
- fix paths for new android location
- Improve `call-create-baseline` params
- fix task needs
**Test plan**
- Run CI. [Sample(without sentry)](https://github.com/makeevrserg/Flipper-Android-App/actions/runs/8855544119)

Fix job workflow needs

---

CHANGELOG.md
components/bridge/connection/orchestrator/impl/src/main/kotlin/com/flipperdevices/bridge/connection/ble/impl/FDeviceHolder.kt
components/bridge/connection/orchestrator/impl/src/main/kotlin/com/flipperdevices/bridge/connection/ble/impl/FDeviceOrchestratorImpl.kt
components/bridge/connection/sample/src/main/kotlin/com/flipperdevices/bridge/connection/screens/device/viewmodel/PingViewModel.kt
components/bridge/connection/transport/ble/impl/src/main/kotlin/com/flipperdevices/bridge/connection/transport/ble/impl/BleDeviceConnectionApiImpl.kt
components/bridge/connection/transport/ble/impl/src/main/kotlin/com/flipperdevices/bridge/connection/transport/ble/impl/api/FBleApiImpl.kt
components/bridge/connection/transport/ble/impl/src/main/kotlin/com/flipperdevices/bridge/connection/transport/ble/impl/api/FBleApiWithSerial.kt
components/bridge/connection/transport/ble/impl/src/main/kotlin/com/flipperdevices/bridge/connection/transport/ble/impl/api/FBleApiWithSerialFactory.kt
components/bridge/connection/transport/ble/impl/src/main/kotlin/com/flipperdevices/bridge/connection/transport/ble/impl/di/BleDeviceConnectionModule.kt
components/bridge/connection/transport/ble/impl/src/main/kotlin/com/flipperdevices/bridge/connection/transport/ble/impl/serial/FSerialDeviceApiWrapper.kt
components/bridge/connection/transport/ble/impl/src/main/kotlin/com/flipperdevices/bridge/connection/transport/ble/impl/serial/FSerialOverflowThrottler.kt
components/bridge/connection/transport/ble/impl/src/main/kotlin/com/flipperdevices/bridge/connection/transport/ble/impl/serial/FSerialUnsafeApiImpl.kt
components/bridge/connection/transport/ble/impl/src/test/kotlin/com/flipperdevices/bridge/connection/ble/impl/serial/FSerialOverflowThrottlerTest.kt

**Background**
Right now we have new connection orchestrator with broken sample
**Changes**
- Fix send and receive bytes flow
**Test plan**
Try run connection sample and check ping

Fix ping pong in new BLE sample

---

.github/renovate.json5
CHANGELOG.md
build-logic/plugins/convention/src/main/kotlin/flipper.android-app.gradle.kts
gradle/libs.versions.toml

**Background**
Try update sentry gradle plugin
**Changes**
- Update sentry gradle plugin from 4.4.1 to 4.5.0
- Disable telemetry
- Enable debug
**Test plan**
Try run `./gradlew assembleInternal`

Enable debug for sentry plugin and disable telemetry

---

components/core/ui/tabswitch/src/main/java/com/flipperdevices/core/ui/tabswitch/ComposableTabswitch.kt
components/core/ui/theme/src/main/kotlin/com/flipperdevices/core/ui/theme/FlipperTheme.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/compose/info/ComposableFirmwareVersion.kt
components/info/shared/src/main/java/com/flipperdevices/info/shared/ComposableDeviceInfoRow.kt
components/nfc/mfkey32/screen/src/main/java/com/flipperdevices/nfc/mfkey32/screen/composable/progressbar/error/ComposableMfKey32Error.kt

**Background**
CI is angry with new detekt rule
**Changes**
- Fixed new detekt rule 
**Test plan**
- run ci/cd

Fix detekt issues

---

CHANGELOG.md
components/info/impl/src/main/java/com/flipperdevices/info/impl/compose/info/ComposableInfoCard.kt
components/info/shared/src/main/java/com/flipperdevices/info/shared/ButtonElementCard.kt
components/updater/card/src/main/java/com/flipperdevices/updater/card/model/BatteryState.kt

**Changes**
- [FIX] Battery level charge
- [FIX] Button arrow tint

Fix battery level and arrow tint

---

.github/workflows/call-create-baseline.yml
.github/workflows/gradle-wrapper-validation.yml
.github/workflows/internal.yml
.github/workflows/pr.yml
.github/workflows/pr_changelog.yml
.github/workflows/pr_gradle.yml
.github/workflows/release.yml

**Background**
Switch to self-hosted github runners
**Changes**
Switch to self-hosted github runners
**Test plan**
All PR should works

Switch to self-hosted github runners

---

CHANGELOG.md
components/keyedit/impl/src/main/java/com/flipperdevices/keyedit/impl/composable/ComposableEditScreen.kt
components/share/receive/src/main/java/com/flipperdevices/share/receive/composable/screens/ComposableKeySaveScreen.kt

**Background**
Right now long keys don't show the save button
**Changes**
- Add scroll to key card
**Test plan**
Try open large key

Fix scroll on save key

---

CHANGELOG.md
components/bridge/dao/api/src/main/java/com/flipperdevices/bridge/dao/api/model/WidgetData.kt
components/widget/impl/src/main/AndroidManifest.xml
components/widget/impl/src/main/java/com/flipperdevices/widget/impl/broadcast/StartChainBuilder.kt
components/widget/impl/src/main/java/com/flipperdevices/widget/impl/broadcast/WidgetBroadcastReceiver.kt
components/widget/impl/src/main/java/com/flipperdevices/widget/impl/providers/BaseWidgetProvider.kt
components/widget/impl/src/main/java/com/flipperdevices/widget/impl/providers/OneClickWidgetProvider.kt
components/widget/impl/src/main/res/values/strings.xml
components/widget/impl/src/main/res/xml/widget_onetap.xml

**Background**
Right now, we don't have the ability to send a single signal
Fix #460
**Changes**
- Add one tap widget which disable signal automaticly
**Test plan**
Try use new widget from android widget menu

Add onetap widget

---

.github/renovate.json5
CHANGELOG.md
build-logic/plugins/convention/src/main/kotlin/flipper.ktorfit-multiplatform.gradle.kts
build-logic/plugins/convention/src/main/kotlin/flipper.ktorfit.gradle.kts
components/faphub/dao/network/build.gradle.kts
components/faphub/dao/network/src/main/java/com/flipperdevices/faphub/dao/network/ktorfit/KtorfitModule.kt
components/remote-controls/api-backend/build.gradle.kts
components/remote-controls/api-backend/src/commonMain/kotlin/com/flipperdevices/ifrmvp/api/infrared/InfraredBackendApi.kt
components/remote-controls/api-backend/src/commonMain/kotlin/com/flipperdevices/ifrmvp/backend/model/PagesLayoutBackendModel.kt
components/remote-controls/grid/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/grid/presentation/data/BackendPagesRepository.kt
gradle/libs.versions.toml

**Background**
Right now we have some strange crashes which caused by compose compiler generated code
**Changes**
- Try use kotlin 2.0.20-Beta2 
**Test plan**
Rollout to google play

Try use kotlin 2.0.20-Beta2 for bypass compose compiler exception

---

CHANGELOG.md
components/faphub/installation/manifest/impl/src/main/java/com/flipperdevices/faphub/installation/manifest/impl/utils/FapManifestsLoader.kt

**Background**
Right now manifest caching works only as read only storage
**Changes**
- Invalidate cache
**Test plan**
Try load manifests twice

Fix manifest caching

---

CHANGELOG.md
components/faphub/installedtab/impl/src/test/kotlin/com/flipperdevices/faphub/installedtab/impl/viewmodel/InstalledFapsUidsProducerTest.kt

**Background**
Right now our tests sometimes flaky
**Changes**
Fix race condition in InstalledFapsUidsProducerTest
**Test plan**
Try launch InstalledFapsUidsProducerTest test

Fix flaky test InstalledFapsUidsProducerTest

---

CHANGELOG.md
components/remote-controls/grid/saved/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/grid/local/composable/LocalGridComposable.kt
components/remote-controls/grid/saved/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/grid/local/composable/components/ComposableRemoteDialogHowToUse.kt
components/remote-controls/grid/saved/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/grid/local/composable/components/GridOptions.kt
components/remote-controls/grid/saved/impl/src/main/res/drawable/ir_flipper_format_dark.xml
components/remote-controls/grid/saved/impl/src/main/res/drawable/ir_flipper_format_light.xml
components/remote-controls/grid/saved/impl/src/main/res/values/strings.xml

**Background**
How to use dialog will help new users to understand
**Changes**
- Add how to use dialog
**Test plan**
- Open saved remote and click how to use

Add how to use to remote controls

---

CHANGELOG.md
components/bridge/api/src/main/java/com/flipperdevices/bridge/api/utils/Constants.kt
components/bridge/dao/api/src/commonMain/kotlin/com/flipperdevices/bridge/dao/api/model/FlipperFilePath.kt
components/bridge/rpcinfo/api/src/main/java/com/flipperdevices/bridge/rpcinfo/model/FlipperStorageInformation.kt
components/bridge/rpcinfo/impl/src/test/java/com/flipperdevices/bridge/rpcinfo/impl/model/FlipperStorageInformationTest.kt
components/debug/stresstest/src/main/java/com/flipperdevices/debug/stresstest/viewmodel/StressTestViewModel.kt
components/filemanager/impl/src/main/java/com/flipperdevices/filemanager/impl/model/FileItem.kt
components/info/impl/src/main/java/com/flipperdevices/info/impl/compose/elements/ComposableInfoCardContent.kt
components/newfilemanager/impl/src/androidMain/kotlin/com/flipperdevices/newfilemanager/impl/model/FileItem.kt

**Background**
Right now `/any` is deprecated
**Changes**
- Remove internal storage display
**Test plan**
Try open app and check that `/any` not use in whole app

Replace /any/ to /ext/

---

components/bridge/connection/service/api/build.gradle.kts
components/bridge/connection/service/api/src/commonMain/kotlin/com/flipperdevices/bridge/connection/service/api/FConnectionService.kt
components/bridge/connection/service/impl/build.gradle.kts
components/bridge/connection/service/impl/src/commonMain/kotlin/com/flipperdevices/bridge/connection/service/impl/FConnectionServiceImpl.kt
instances/android/app/build.gradle.kts
instances/android/app/src/main/java/com/flipperdevices/app/FlipperApplication.kt
instances/android/app/src/main/java/com/flipperdevices/app/di/MainComponent.kt
settings.gradle.kts

**Background**
Device connection service for new API
**Changes**
- Add new connection service
- Start it in application
**Test plan**
- Install flipper from branch, open int
- See it now bottom bar display connection state and synchronization

Connection service for new API

---

components/archive/impl/build.gradle.kts
components/archive/impl/src/main/java/com/flipperdevices/archive/impl/composable/ComposableArchive.kt
components/archive/impl/src/main/java/com/flipperdevices/archive/impl/composable/page/ArchiveProgressScreen.kt
components/archive/impl/src/main/java/com/flipperdevices/archive/impl/viewmodel/SpeedViewModel.kt
components/bridge/connection/config/api/src/commonMain/kotlin/com/flipperdevices/bridge/connection/config/api/FDevicePersistedStorage.kt
components/bridge/connection/config/impl/src/commonMain/kotlin/com/flipperdevices/bridge/connection/config/impl/FDevicePersistedStorageImpl.kt
components/bridge/connection/feature/protocolversion/impl/src/commonMain/kotlin/com/flipperdevices/bridge/connection/feature/protocolversion/impl/api/FSdkVersionFeatureFactoryImpl.kt

**Background**
Migrate archive to new api
**Changes**
- Replaced fserial speed api
**Test plan**
- Open archive and see sync ui now displays speed

Migrate archive to new api

---

components/bridge/connection/feature/emulate/api/src/commonMain/kotlin/com/flipperdevices/bridge/connection/feature/emulate/api/helpers/StartEmulateHelper.kt
components/bridge/connection/feature/emulate/impl/src/commonMain/kotlin/com/flipperdevices/bridge/connection/feature/emulate/impl/api/helpers/StartEmulateHelperImpl.kt
components/infrared/api/build.gradle.kts
components/infrared/api/src/main/kotlin/com/flipperdevices/infrared/api/InfraredConnectionApi.kt
components/infrared/impl/build.gradle.kts
components/infrared/impl/src/main/kotlin/com/flipperdevices/infrared/impl/api/InfraredConnectionApiImpl.kt
components/infrared/impl/src/main/kotlin/com/flipperdevices/infrared/impl/viewmodel/InfraredViewModel.kt
components/keyscreen/api/build.gradle.kts
components/keyscreen/impl/build.gradle.kts
components/remote-controls/grid/remote/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/grid/remote/presentation/viewmodel/ConnectionViewModel.kt
components/remote-controls/grid/saved/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/grid/local/presentation/viewmodel/ConnectionViewModel.kt
components/remote-controls/setup/impl/src/main/kotlin/com/flipperdevices/remotecontrols/impl/setup/presentation/viewmodel/ConnectionViewModel.kt

**Background**
Migrated infrared module on new api
**Changes**
- Migrated one module
- Also removed unused bridge api in keyscreen
**Test plan**
- Open app and see infrared emulation works

Migrate infrared to new api

---

components/bridge/connection/service/api/src/commonMain/kotlin/com/flipperdevices/bridge/connection/service/api/FConnectionService.kt
components/bridge/connection/service/impl/src/commonMain/kotlin/com/flipperdevices/bridge/connection/service/impl/FConnectionServiceImpl.kt
components/keyscreen/impl/build.gradle.kts
components/wearable/emulate/handheld/impl/build.gradle.kts
components/wearable/emulate/handheld/impl/src/main/java/com/flipperdevices/wearable/emulate/handheld/impl/di/WearServiceComponent.kt
components/wearable/emulate/handheld/impl/src/main/java/com/flipperdevices/wearable/emulate/handheld/impl/di/WearServiceComponentImpl.kt
components/wearable/emulate/handheld/impl/src/main/java/com/flipperdevices/wearable/emulate/handheld/impl/request/WearableAppStateProcessor.kt
components/wearable/emulate/handheld/impl/src/main/java/com/flipperdevices/wearable/emulate/handheld/impl/request/WearableFlipperStatusProcessor.kt
components/widget/impl/build.gradle.kts
components/widget/impl/src/main/java/com/flipperdevices/widget/impl/tasks/WaitForEmulateEndWorker.kt
components/widget/impl/src/main/java/com/flipperdevices/widget/impl/tasks/WaitingForFlipperConnectWorker.kt

**Background**
Migrate other half of wearable and widget to new ble api
**Changes**
- Migrate wearable to new api
- Migrate widget to new api
**Test plan**
- Assemble and launch

migrate widget and wearable to new ble api
